package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class Banner implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.id
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.page
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private String page;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.position
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.pic_order
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private Integer picOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.title
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.content
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.pic_href
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private String picHref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.pic_url
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.add_time
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.update_time
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.del_flag
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table banner
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.id
	 * @return  the value of banner.id
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.id
	 * @param id  the value for banner.id
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.page
	 * @return  the value of banner.page
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public String getPage() {
		return page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.page
	 * @param page  the value for banner.page
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setPage(String page) {
		this.page = page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.position
	 * @return  the value of banner.position
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.position
	 * @param position  the value for banner.position
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.pic_order
	 * @return  the value of banner.pic_order
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public Integer getPicOrder() {
		return picOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.pic_order
	 * @param picOrder  the value for banner.pic_order
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setPicOrder(Integer picOrder) {
		this.picOrder = picOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.title
	 * @return  the value of banner.title
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.title
	 * @param title  the value for banner.title
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.content
	 * @return  the value of banner.content
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.content
	 * @param content  the value for banner.content
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.pic_href
	 * @return  the value of banner.pic_href
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public String getPicHref() {
		return picHref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.pic_href
	 * @param picHref  the value for banner.pic_href
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setPicHref(String picHref) {
		this.picHref = picHref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.pic_url
	 * @return  the value of banner.pic_url
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.pic_url
	 * @param picUrl  the value for banner.pic_url
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.add_time
	 * @return  the value of banner.add_time
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.add_time
	 * @param addTime  the value for banner.add_time
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.update_time
	 * @return  the value of banner.update_time
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.update_time
	 * @param updateTime  the value for banner.update_time
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.del_flag
	 * @return  the value of banner.del_flag
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.del_flag
	 * @param delFlag  the value for banner.del_flag
	 * @mbggenerated  Mon Aug 15 16:36:53 GMT+08:00 2016
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}
}