package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class FriendLink implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_link.id
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_link.title
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_link.href
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_link.orders
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_link.add_time
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_link.update_time
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_link.del_flag
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    private Byte delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friend_link
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_link.id
     *
     * @return the value of friend_link.id
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_link.id
     *
     * @param id the value for friend_link.id
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_link.title
     *
     * @return the value of friend_link.title
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_link.title
     *
     * @param title the value for friend_link.title
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_link.href
     *
     * @return the value of friend_link.href
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_link.href
     *
     * @param href the value for friend_link.href
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_link.orders
     *
     * @return the value of friend_link.orders
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_link.orders
     *
     * @param orders the value for friend_link.orders
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_link.add_time
     *
     * @return the value of friend_link.add_time
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_link.add_time
     *
     * @param addTime the value for friend_link.add_time
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_link.update_time
     *
     * @return the value of friend_link.update_time
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_link.update_time
     *
     * @param updateTime the value for friend_link.update_time
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_link.del_flag
     *
     * @return the value of friend_link.del_flag
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_link.del_flag
     *
     * @param delFlag the value for friend_link.del_flag
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }
}