package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class LiveGift implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.id
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.live_id
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private Integer liveId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.name
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.num
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.money
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private String money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.dates
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private Date dates;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.times
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private Integer times;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.add_time
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.update_time
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column live_gift.del_flag
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table live_gift
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.id
	 * @return  the value of live_gift.id
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.id
	 * @param id  the value for live_gift.id
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.live_id
	 * @return  the value of live_gift.live_id
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public Integer getLiveId() {
		return liveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.live_id
	 * @param liveId  the value for live_gift.live_id
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setLiveId(Integer liveId) {
		this.liveId = liveId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.name
	 * @return  the value of live_gift.name
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.name
	 * @param name  the value for live_gift.name
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.num
	 * @return  the value of live_gift.num
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.num
	 * @param num  the value for live_gift.num
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.money
	 * @return  the value of live_gift.money
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public String getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.money
	 * @param money  the value for live_gift.money
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setMoney(String money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.dates
	 * @return  the value of live_gift.dates
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public Date getDates() {
		return dates;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.dates
	 * @param dates  the value for live_gift.dates
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setDates(Date dates) {
		this.dates = dates;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.times
	 * @return  the value of live_gift.times
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public Integer getTimes() {
		return times;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.times
	 * @param times  the value for live_gift.times
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setTimes(Integer times) {
		this.times = times;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.add_time
	 * @return  the value of live_gift.add_time
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.add_time
	 * @param addTime  the value for live_gift.add_time
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.update_time
	 * @return  the value of live_gift.update_time
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.update_time
	 * @param updateTime  the value for live_gift.update_time
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column live_gift.del_flag
	 * @return  the value of live_gift.del_flag
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column live_gift.del_flag
	 * @param delFlag  the value for live_gift.del_flag
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}
}