package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class Notice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.create_id
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.status
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.add_time
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.update_time
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.del_flag
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    private Byte delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notice
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.create_id
     *
     * @return the value of notice.create_id
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.create_id
     *
     * @param createId the value for notice.create_id
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.status
     *
     * @return the value of notice.status
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.status
     *
     * @param status the value for notice.status
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.content
     *
     * @return the value of notice.content
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.content
     *
     * @param content the value for notice.content
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.add_time
     *
     * @return the value of notice.add_time
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.add_time
     *
     * @param addTime the value for notice.add_time
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.update_time
     *
     * @return the value of notice.update_time
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.update_time
     *
     * @param updateTime the value for notice.update_time
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.del_flag
     *
     * @return the value of notice.del_flag
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.del_flag
     *
     * @param delFlag the value for notice.del_flag
     *
     * @mbggenerated Thu Aug 11 16:14:40 GMT+08:00 2016
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }
}