package org.bees.biz.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PackagesOrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	protected int limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	protected int limitEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	protected String groupByClause;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public PackagesOrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setGroupByClause(String groupByClause) {
		this.groupByClause = groupByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public String getGroupByClause() {
		return groupByClause;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUidIsNull() {
			addCriterion("uid is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("uid is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(Integer value) {
			addCriterion("uid =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(Integer value) {
			addCriterion("uid <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(Integer value) {
			addCriterion("uid >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(Integer value) {
			addCriterion("uid >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(Integer value) {
			addCriterion("uid <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(Integer value) {
			addCriterion("uid <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<Integer> values) {
			addCriterion("uid in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<Integer> values) {
			addCriterion("uid not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(Integer value1, Integer value2) {
			addCriterion("uid between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(Integer value1, Integer value2) {
			addCriterion("uid not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andPackageIdIsNull() {
			addCriterion("package_id is null");
			return (Criteria) this;
		}

		public Criteria andPackageIdIsNotNull() {
			addCriterion("package_id is not null");
			return (Criteria) this;
		}

		public Criteria andPackageIdEqualTo(Integer value) {
			addCriterion("package_id =", value, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageIdNotEqualTo(Integer value) {
			addCriterion("package_id <>", value, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageIdGreaterThan(Integer value) {
			addCriterion("package_id >", value, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("package_id >=", value, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageIdLessThan(Integer value) {
			addCriterion("package_id <", value, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageIdLessThanOrEqualTo(Integer value) {
			addCriterion("package_id <=", value, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageIdIn(List<Integer> values) {
			addCriterion("package_id in", values, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageIdNotIn(List<Integer> values) {
			addCriterion("package_id not in", values, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageIdBetween(Integer value1, Integer value2) {
			addCriterion("package_id between", value1, value2, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageIdNotBetween(Integer value1, Integer value2) {
			addCriterion("package_id not between", value1, value2, "packageId");
			return (Criteria) this;
		}

		public Criteria andPackageNameIsNull() {
			addCriterion("package_name is null");
			return (Criteria) this;
		}

		public Criteria andPackageNameIsNotNull() {
			addCriterion("package_name is not null");
			return (Criteria) this;
		}

		public Criteria andPackageNameEqualTo(String value) {
			addCriterion("package_name =", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameNotEqualTo(String value) {
			addCriterion("package_name <>", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameGreaterThan(String value) {
			addCriterion("package_name >", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameGreaterThanOrEqualTo(String value) {
			addCriterion("package_name >=", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameLessThan(String value) {
			addCriterion("package_name <", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameLessThanOrEqualTo(String value) {
			addCriterion("package_name <=", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameLike(String value) {
			addCriterion("package_name like", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameNotLike(String value) {
			addCriterion("package_name not like", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameIn(List<String> values) {
			addCriterion("package_name in", values, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameNotIn(List<String> values) {
			addCriterion("package_name not in", values, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameBetween(String value1, String value2) {
			addCriterion("package_name between", value1, value2, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameNotBetween(String value1, String value2) {
			addCriterion("package_name not between", value1, value2,
					"packageName");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdIsNull() {
			addCriterion("package_price_id is null");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdIsNotNull() {
			addCriterion("package_price_id is not null");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdEqualTo(Integer value) {
			addCriterion("package_price_id =", value, "packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdNotEqualTo(Integer value) {
			addCriterion("package_price_id <>", value, "packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdGreaterThan(Integer value) {
			addCriterion("package_price_id >", value, "packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("package_price_id >=", value, "packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdLessThan(Integer value) {
			addCriterion("package_price_id <", value, "packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdLessThanOrEqualTo(Integer value) {
			addCriterion("package_price_id <=", value, "packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdIn(List<Integer> values) {
			addCriterion("package_price_id in", values, "packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdNotIn(List<Integer> values) {
			addCriterion("package_price_id not in", values, "packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdBetween(Integer value1, Integer value2) {
			addCriterion("package_price_id between", value1, value2,
					"packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePriceIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("package_price_id not between", value1, value2,
					"packagePriceId");
			return (Criteria) this;
		}

		public Criteria andPackagePicIsNull() {
			addCriterion("package_pic is null");
			return (Criteria) this;
		}

		public Criteria andPackagePicIsNotNull() {
			addCriterion("package_pic is not null");
			return (Criteria) this;
		}

		public Criteria andPackagePicEqualTo(String value) {
			addCriterion("package_pic =", value, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicNotEqualTo(String value) {
			addCriterion("package_pic <>", value, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicGreaterThan(String value) {
			addCriterion("package_pic >", value, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicGreaterThanOrEqualTo(String value) {
			addCriterion("package_pic >=", value, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicLessThan(String value) {
			addCriterion("package_pic <", value, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicLessThanOrEqualTo(String value) {
			addCriterion("package_pic <=", value, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicLike(String value) {
			addCriterion("package_pic like", value, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicNotLike(String value) {
			addCriterion("package_pic not like", value, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicIn(List<String> values) {
			addCriterion("package_pic in", values, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicNotIn(List<String> values) {
			addCriterion("package_pic not in", values, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicBetween(String value1, String value2) {
			addCriterion("package_pic between", value1, value2, "packagePic");
			return (Criteria) this;
		}

		public Criteria andPackagePicNotBetween(String value1, String value2) {
			addCriterion("package_pic not between", value1, value2,
					"packagePic");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(String value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(String value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(String value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(String value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(String value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(String value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLike(String value) {
			addCriterion("price like", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotLike(String value) {
			addCriterion("price not like", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<String> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<String> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(String value1, String value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(String value1, String value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andPayTypeIsNull() {
			addCriterion("pay_type is null");
			return (Criteria) this;
		}

		public Criteria andPayTypeIsNotNull() {
			addCriterion("pay_type is not null");
			return (Criteria) this;
		}

		public Criteria andPayTypeEqualTo(Byte value) {
			addCriterion("pay_type =", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotEqualTo(Byte value) {
			addCriterion("pay_type <>", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeGreaterThan(Byte value) {
			addCriterion("pay_type >", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("pay_type >=", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeLessThan(Byte value) {
			addCriterion("pay_type <", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeLessThanOrEqualTo(Byte value) {
			addCriterion("pay_type <=", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeIn(List<Byte> values) {
			addCriterion("pay_type in", values, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotIn(List<Byte> values) {
			addCriterion("pay_type not in", values, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeBetween(Byte value1, Byte value2) {
			addCriterion("pay_type between", value1, value2, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("pay_type not between", value1, value2, "payType");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeIsNull() {
			addCriterion("submit_time is null");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeIsNotNull() {
			addCriterion("submit_time is not null");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeEqualTo(Date value) {
			addCriterion("submit_time =", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeNotEqualTo(Date value) {
			addCriterion("submit_time <>", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeGreaterThan(Date value) {
			addCriterion("submit_time >", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("submit_time >=", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeLessThan(Date value) {
			addCriterion("submit_time <", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeLessThanOrEqualTo(Date value) {
			addCriterion("submit_time <=", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeIn(List<Date> values) {
			addCriterion("submit_time in", values, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeNotIn(List<Date> values) {
			addCriterion("submit_time not in", values, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeBetween(Date value1, Date value2) {
			addCriterion("submit_time between", value1, value2, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeNotBetween(Date value1, Date value2) {
			addCriterion("submit_time not between", value1, value2,
					"submitTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNull() {
			addCriterion("pay_time is null");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNotNull() {
			addCriterion("pay_time is not null");
			return (Criteria) this;
		}

		public Criteria andPayTimeEqualTo(Date value) {
			addCriterion("pay_time =", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotEqualTo(Date value) {
			addCriterion("pay_time <>", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThan(Date value) {
			addCriterion("pay_time >", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pay_time >=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThan(Date value) {
			addCriterion("pay_time <", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThanOrEqualTo(Date value) {
			addCriterion("pay_time <=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIn(List<Date> values) {
			addCriterion("pay_time in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotIn(List<Date> values) {
			addCriterion("pay_time not in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeBetween(Date value1, Date value2) {
			addCriterion("pay_time between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotBetween(Date value1, Date value2) {
			addCriterion("pay_time not between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("start_time is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("start_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Date value) {
			addCriterion("start_time =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Date value) {
			addCriterion("start_time <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Date value) {
			addCriterion("start_time >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("start_time >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Date value) {
			addCriterion("start_time <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Date value) {
			addCriterion("start_time <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Date> values) {
			addCriterion("start_time in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Date> values) {
			addCriterion("start_time not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Date value1, Date value2) {
			addCriterion("start_time between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Date value1, Date value2) {
			addCriterion("start_time not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterion("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterion("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterion("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterion("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterion("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterion("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterion("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterion("end_time between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterion("end_time not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("comment is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("comment is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("comment =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("comment <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("comment >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("comment >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("comment <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("comment <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("comment like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("comment not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("comment in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("comment not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("comment between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("comment not between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentTimeIsNull() {
			addCriterion("comment_time is null");
			return (Criteria) this;
		}

		public Criteria andCommentTimeIsNotNull() {
			addCriterion("comment_time is not null");
			return (Criteria) this;
		}

		public Criteria andCommentTimeEqualTo(Date value) {
			addCriterion("comment_time =", value, "commentTime");
			return (Criteria) this;
		}

		public Criteria andCommentTimeNotEqualTo(Date value) {
			addCriterion("comment_time <>", value, "commentTime");
			return (Criteria) this;
		}

		public Criteria andCommentTimeGreaterThan(Date value) {
			addCriterion("comment_time >", value, "commentTime");
			return (Criteria) this;
		}

		public Criteria andCommentTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("comment_time >=", value, "commentTime");
			return (Criteria) this;
		}

		public Criteria andCommentTimeLessThan(Date value) {
			addCriterion("comment_time <", value, "commentTime");
			return (Criteria) this;
		}

		public Criteria andCommentTimeLessThanOrEqualTo(Date value) {
			addCriterion("comment_time <=", value, "commentTime");
			return (Criteria) this;
		}

		public Criteria andCommentTimeIn(List<Date> values) {
			addCriterion("comment_time in", values, "commentTime");
			return (Criteria) this;
		}

		public Criteria andCommentTimeNotIn(List<Date> values) {
			addCriterion("comment_time not in", values, "commentTime");
			return (Criteria) this;
		}

		public Criteria andCommentTimeBetween(Date value1, Date value2) {
			addCriterion("comment_time between", value1, value2, "commentTime");
			return (Criteria) this;
		}

		public Criteria andCommentTimeNotBetween(Date value1, Date value2) {
			addCriterion("comment_time not between", value1, value2,
					"commentTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Byte value) {
			addCriterion("del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Byte value) {
			addCriterion("del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Byte value) {
			addCriterion("del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Byte value) {
			addCriterion("del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
			addCriterion("del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Byte> values) {
			addCriterion("del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Byte> values) {
			addCriterion("del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Byte value1, Byte value2) {
			addCriterion("del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table packages_order
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 31 00:22:21 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}