package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class PackagesOrder implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.id
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.uid
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.package_id
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Integer packageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.package_name
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private String packageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.package_price_id
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Integer packagePriceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.package_pic
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private String packagePic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.price
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.status
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.pay_type
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Byte payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.submit_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Date submitTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.pay_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.start_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.end_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.comment
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.comment_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Date commentTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.add_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.update_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_order.del_flag
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table packages_order
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.id
	 * @return  the value of packages_order.id
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.id
	 * @param id  the value for packages_order.id
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.uid
	 * @return  the value of packages_order.uid
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.uid
	 * @param uid  the value for packages_order.uid
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.package_id
	 * @return  the value of packages_order.package_id
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Integer getPackageId() {
		return packageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.package_id
	 * @param packageId  the value for packages_order.package_id
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.package_name
	 * @return  the value of packages_order.package_name
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public String getPackageName() {
		return packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.package_name
	 * @param packageName  the value for packages_order.package_name
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.package_price_id
	 * @return  the value of packages_order.package_price_id
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Integer getPackagePriceId() {
		return packagePriceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.package_price_id
	 * @param packagePriceId  the value for packages_order.package_price_id
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setPackagePriceId(Integer packagePriceId) {
		this.packagePriceId = packagePriceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.package_pic
	 * @return  the value of packages_order.package_pic
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public String getPackagePic() {
		return packagePic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.package_pic
	 * @param packagePic  the value for packages_order.package_pic
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setPackagePic(String packagePic) {
		this.packagePic = packagePic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.price
	 * @return  the value of packages_order.price
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.price
	 * @param price  the value for packages_order.price
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.status
	 * @return  the value of packages_order.status
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.status
	 * @param status  the value for packages_order.status
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.pay_type
	 * @return  the value of packages_order.pay_type
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Byte getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.pay_type
	 * @param payType  the value for packages_order.pay_type
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setPayType(Byte payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.submit_time
	 * @return  the value of packages_order.submit_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Date getSubmitTime() {
		return submitTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.submit_time
	 * @param submitTime  the value for packages_order.submit_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.pay_time
	 * @return  the value of packages_order.pay_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.pay_time
	 * @param payTime  the value for packages_order.pay_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.start_time
	 * @return  the value of packages_order.start_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.start_time
	 * @param startTime  the value for packages_order.start_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.end_time
	 * @return  the value of packages_order.end_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.end_time
	 * @param endTime  the value for packages_order.end_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.comment
	 * @return  the value of packages_order.comment
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.comment
	 * @param comment  the value for packages_order.comment
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.comment_time
	 * @return  the value of packages_order.comment_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Date getCommentTime() {
		return commentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.comment_time
	 * @param commentTime  the value for packages_order.comment_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.add_time
	 * @return  the value of packages_order.add_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.add_time
	 * @param addTime  the value for packages_order.add_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.update_time
	 * @return  the value of packages_order.update_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.update_time
	 * @param updateTime  the value for packages_order.update_time
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_order.del_flag
	 * @return  the value of packages_order.del_flag
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_order.del_flag
	 * @param delFlag  the value for packages_order.del_flag
	 * @mbggenerated  Thu Nov 24 01:44:17 CST 2016
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}
}