package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class Packages implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.id
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.name
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.title_one
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private String titleOne;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.title_two
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private String titleTwo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.title_three
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private String titleThree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.pic
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private String pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.content
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.add_time
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.update_time
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages.del_flag
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table packages
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.id
	 * @return  the value of packages.id
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.id
	 * @param id  the value for packages.id
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.name
	 * @return  the value of packages.name
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.name
	 * @param name  the value for packages.name
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.title_one
	 * @return  the value of packages.title_one
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public String getTitleOne() {
		return titleOne;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.title_one
	 * @param titleOne  the value for packages.title_one
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setTitleOne(String titleOne) {
		this.titleOne = titleOne;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.title_two
	 * @return  the value of packages.title_two
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public String getTitleTwo() {
		return titleTwo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.title_two
	 * @param titleTwo  the value for packages.title_two
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setTitleTwo(String titleTwo) {
		this.titleTwo = titleTwo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.title_three
	 * @return  the value of packages.title_three
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public String getTitleThree() {
		return titleThree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.title_three
	 * @param titleThree  the value for packages.title_three
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setTitleThree(String titleThree) {
		this.titleThree = titleThree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.pic
	 * @return  the value of packages.pic
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.pic
	 * @param pic  the value for packages.pic
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.content
	 * @return  the value of packages.content
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.content
	 * @param content  the value for packages.content
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.add_time
	 * @return  the value of packages.add_time
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.add_time
	 * @param addTime  the value for packages.add_time
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.update_time
	 * @return  the value of packages.update_time
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.update_time
	 * @param updateTime  the value for packages.update_time
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages.del_flag
	 * @return  the value of packages.del_flag
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages.del_flag
	 * @param delFlag  the value for packages.del_flag
	 * @mbggenerated  Fri Sep 09 22:47:28 CST 2016
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}
}