package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class Product implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.name
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.pic
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	private String pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.href
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	private String href;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.position
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	private Byte position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.add_time
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.update_time
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.del_flag
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.name
	 * @return  the value of product.name
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.name
	 * @param name  the value for product.name
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.pic
	 * @return  the value of product.pic
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.pic
	 * @param pic  the value for product.pic
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.href
	 * @return  the value of product.href
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public String getHref() {
		return href;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.href
	 * @param href  the value for product.href
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public void setHref(String href) {
		this.href = href;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.position
	 * @return  the value of product.position
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public Byte getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.position
	 * @param position  the value for product.position
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public void setPosition(Byte position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.add_time
	 * @return  the value of product.add_time
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.add_time
	 * @param addTime  the value for product.add_time
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.update_time
	 * @return  the value of product.update_time
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.update_time
	 * @param updateTime  the value for product.update_time
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.del_flag
	 * @return  the value of product.del_flag
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.del_flag
	 * @param delFlag  the value for product.del_flag
	 * @mbggenerated  Fri Nov 04 10:48:09 GMT+08:00 2016
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}
}