package org.bees.biz.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskSignExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	protected int limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	protected int limitEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	protected String groupByClause;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public TaskSignExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setGroupByClause(String groupByClause) {
		this.groupByClause = groupByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public String getGroupByClause() {
		return groupByClause;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNull() {
			addCriterion("task_id is null");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNotNull() {
			addCriterion("task_id is not null");
			return (Criteria) this;
		}

		public Criteria andTaskIdEqualTo(Integer value) {
			addCriterion("task_id =", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotEqualTo(Integer value) {
			addCriterion("task_id <>", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThan(Integer value) {
			addCriterion("task_id >", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("task_id >=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThan(Integer value) {
			addCriterion("task_id <", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
			addCriterion("task_id <=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdIn(List<Integer> values) {
			addCriterion("task_id in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotIn(List<Integer> values) {
			addCriterion("task_id not in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdBetween(Integer value1, Integer value2) {
			addCriterion("task_id between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
			addCriterion("task_id not between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andUidIsNull() {
			addCriterion("uid is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("uid is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(Integer value) {
			addCriterion("uid =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(Integer value) {
			addCriterion("uid <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(Integer value) {
			addCriterion("uid >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(Integer value) {
			addCriterion("uid >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(Integer value) {
			addCriterion("uid <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(Integer value) {
			addCriterion("uid <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<Integer> values) {
			addCriterion("uid in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<Integer> values) {
			addCriterion("uid not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(Integer value1, Integer value2) {
			addCriterion("uid between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(Integer value1, Integer value2) {
			addCriterion("uid not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andBidStatusIsNull() {
			addCriterion("bid_status is null");
			return (Criteria) this;
		}

		public Criteria andBidStatusIsNotNull() {
			addCriterion("bid_status is not null");
			return (Criteria) this;
		}

		public Criteria andBidStatusEqualTo(Byte value) {
			addCriterion("bid_status =", value, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidStatusNotEqualTo(Byte value) {
			addCriterion("bid_status <>", value, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidStatusGreaterThan(Byte value) {
			addCriterion("bid_status >", value, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("bid_status >=", value, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidStatusLessThan(Byte value) {
			addCriterion("bid_status <", value, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidStatusLessThanOrEqualTo(Byte value) {
			addCriterion("bid_status <=", value, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidStatusIn(List<Byte> values) {
			addCriterion("bid_status in", values, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidStatusNotIn(List<Byte> values) {
			addCriterion("bid_status not in", values, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidStatusBetween(Byte value1, Byte value2) {
			addCriterion("bid_status between", value1, value2, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("bid_status not between", value1, value2, "bidStatus");
			return (Criteria) this;
		}

		public Criteria andBidTimeIsNull() {
			addCriterion("bid_time is null");
			return (Criteria) this;
		}

		public Criteria andBidTimeIsNotNull() {
			addCriterion("bid_time is not null");
			return (Criteria) this;
		}

		public Criteria andBidTimeEqualTo(Date value) {
			addCriterion("bid_time =", value, "bidTime");
			return (Criteria) this;
		}

		public Criteria andBidTimeNotEqualTo(Date value) {
			addCriterion("bid_time <>", value, "bidTime");
			return (Criteria) this;
		}

		public Criteria andBidTimeGreaterThan(Date value) {
			addCriterion("bid_time >", value, "bidTime");
			return (Criteria) this;
		}

		public Criteria andBidTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("bid_time >=", value, "bidTime");
			return (Criteria) this;
		}

		public Criteria andBidTimeLessThan(Date value) {
			addCriterion("bid_time <", value, "bidTime");
			return (Criteria) this;
		}

		public Criteria andBidTimeLessThanOrEqualTo(Date value) {
			addCriterion("bid_time <=", value, "bidTime");
			return (Criteria) this;
		}

		public Criteria andBidTimeIn(List<Date> values) {
			addCriterion("bid_time in", values, "bidTime");
			return (Criteria) this;
		}

		public Criteria andBidTimeNotIn(List<Date> values) {
			addCriterion("bid_time not in", values, "bidTime");
			return (Criteria) this;
		}

		public Criteria andBidTimeBetween(Date value1, Date value2) {
			addCriterion("bid_time between", value1, value2, "bidTime");
			return (Criteria) this;
		}

		public Criteria andBidTimeNotBetween(Date value1, Date value2) {
			addCriterion("bid_time not between", value1, value2, "bidTime");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIsNull() {
			addCriterion("single_price is null");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIsNotNull() {
			addCriterion("single_price is not null");
			return (Criteria) this;
		}

		public Criteria andSinglePriceEqualTo(String value) {
			addCriterion("single_price =", value, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceNotEqualTo(String value) {
			addCriterion("single_price <>", value, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceGreaterThan(String value) {
			addCriterion("single_price >", value, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceGreaterThanOrEqualTo(String value) {
			addCriterion("single_price >=", value, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceLessThan(String value) {
			addCriterion("single_price <", value, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceLessThanOrEqualTo(String value) {
			addCriterion("single_price <=", value, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceLike(String value) {
			addCriterion("single_price like", value, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceNotLike(String value) {
			addCriterion("single_price not like", value, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceIn(List<String> values) {
			addCriterion("single_price in", values, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceNotIn(List<String> values) {
			addCriterion("single_price not in", values, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceBetween(String value1, String value2) {
			addCriterion("single_price between", value1, value2, "singlePrice");
			return (Criteria) this;
		}

		public Criteria andSinglePriceNotBetween(String value1, String value2) {
			addCriterion("single_price not between", value1, value2,
					"singlePrice");
			return (Criteria) this;
		}

		public Criteria andPayStatusIsNull() {
			addCriterion("pay_status is null");
			return (Criteria) this;
		}

		public Criteria andPayStatusIsNotNull() {
			addCriterion("pay_status is not null");
			return (Criteria) this;
		}

		public Criteria andPayStatusEqualTo(Byte value) {
			addCriterion("pay_status =", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusNotEqualTo(Byte value) {
			addCriterion("pay_status <>", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusGreaterThan(Byte value) {
			addCriterion("pay_status >", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("pay_status >=", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusLessThan(Byte value) {
			addCriterion("pay_status <", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusLessThanOrEqualTo(Byte value) {
			addCriterion("pay_status <=", value, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusIn(List<Byte> values) {
			addCriterion("pay_status in", values, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusNotIn(List<Byte> values) {
			addCriterion("pay_status not in", values, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusBetween(Byte value1, Byte value2) {
			addCriterion("pay_status between", value1, value2, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("pay_status not between", value1, value2, "payStatus");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNull() {
			addCriterion("pay_time is null");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNotNull() {
			addCriterion("pay_time is not null");
			return (Criteria) this;
		}

		public Criteria andPayTimeEqualTo(Date value) {
			addCriterion("pay_time =", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotEqualTo(Date value) {
			addCriterion("pay_time <>", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThan(Date value) {
			addCriterion("pay_time >", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pay_time >=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThan(Date value) {
			addCriterion("pay_time <", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThanOrEqualTo(Date value) {
			addCriterion("pay_time <=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIn(List<Date> values) {
			addCriterion("pay_time in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotIn(List<Date> values) {
			addCriterion("pay_time not in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeBetween(Date value1, Date value2) {
			addCriterion("pay_time between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotBetween(Date value1, Date value2) {
			addCriterion("pay_time not between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andOpIdIsNull() {
			addCriterion("op_id is null");
			return (Criteria) this;
		}

		public Criteria andOpIdIsNotNull() {
			addCriterion("op_id is not null");
			return (Criteria) this;
		}

		public Criteria andOpIdEqualTo(Integer value) {
			addCriterion("op_id =", value, "opId");
			return (Criteria) this;
		}

		public Criteria andOpIdNotEqualTo(Integer value) {
			addCriterion("op_id <>", value, "opId");
			return (Criteria) this;
		}

		public Criteria andOpIdGreaterThan(Integer value) {
			addCriterion("op_id >", value, "opId");
			return (Criteria) this;
		}

		public Criteria andOpIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("op_id >=", value, "opId");
			return (Criteria) this;
		}

		public Criteria andOpIdLessThan(Integer value) {
			addCriterion("op_id <", value, "opId");
			return (Criteria) this;
		}

		public Criteria andOpIdLessThanOrEqualTo(Integer value) {
			addCriterion("op_id <=", value, "opId");
			return (Criteria) this;
		}

		public Criteria andOpIdIn(List<Integer> values) {
			addCriterion("op_id in", values, "opId");
			return (Criteria) this;
		}

		public Criteria andOpIdNotIn(List<Integer> values) {
			addCriterion("op_id not in", values, "opId");
			return (Criteria) this;
		}

		public Criteria andOpIdBetween(Integer value1, Integer value2) {
			addCriterion("op_id between", value1, value2, "opId");
			return (Criteria) this;
		}

		public Criteria andOpIdNotBetween(Integer value1, Integer value2) {
			addCriterion("op_id not between", value1, value2, "opId");
			return (Criteria) this;
		}

		public Criteria andOpTimeIsNull() {
			addCriterion("op_time is null");
			return (Criteria) this;
		}

		public Criteria andOpTimeIsNotNull() {
			addCriterion("op_time is not null");
			return (Criteria) this;
		}

		public Criteria andOpTimeEqualTo(Date value) {
			addCriterion("op_time =", value, "opTime");
			return (Criteria) this;
		}

		public Criteria andOpTimeNotEqualTo(Date value) {
			addCriterion("op_time <>", value, "opTime");
			return (Criteria) this;
		}

		public Criteria andOpTimeGreaterThan(Date value) {
			addCriterion("op_time >", value, "opTime");
			return (Criteria) this;
		}

		public Criteria andOpTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("op_time >=", value, "opTime");
			return (Criteria) this;
		}

		public Criteria andOpTimeLessThan(Date value) {
			addCriterion("op_time <", value, "opTime");
			return (Criteria) this;
		}

		public Criteria andOpTimeLessThanOrEqualTo(Date value) {
			addCriterion("op_time <=", value, "opTime");
			return (Criteria) this;
		}

		public Criteria andOpTimeIn(List<Date> values) {
			addCriterion("op_time in", values, "opTime");
			return (Criteria) this;
		}

		public Criteria andOpTimeNotIn(List<Date> values) {
			addCriterion("op_time not in", values, "opTime");
			return (Criteria) this;
		}

		public Criteria andOpTimeBetween(Date value1, Date value2) {
			addCriterion("op_time between", value1, value2, "opTime");
			return (Criteria) this;
		}

		public Criteria andOpTimeNotBetween(Date value1, Date value2) {
			addCriterion("op_time not between", value1, value2, "opTime");
			return (Criteria) this;
		}

		public Criteria andReasonIsNull() {
			addCriterion("reason is null");
			return (Criteria) this;
		}

		public Criteria andReasonIsNotNull() {
			addCriterion("reason is not null");
			return (Criteria) this;
		}

		public Criteria andReasonEqualTo(String value) {
			addCriterion("reason =", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotEqualTo(String value) {
			addCriterion("reason <>", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThan(String value) {
			addCriterion("reason >", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThanOrEqualTo(String value) {
			addCriterion("reason >=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThan(String value) {
			addCriterion("reason <", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThanOrEqualTo(String value) {
			addCriterion("reason <=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLike(String value) {
			addCriterion("reason like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotLike(String value) {
			addCriterion("reason not like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonIn(List<String> values) {
			addCriterion("reason in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotIn(List<String> values) {
			addCriterion("reason not in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonBetween(String value1, String value2) {
			addCriterion("reason between", value1, value2, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotBetween(String value1, String value2) {
			addCriterion("reason not between", value1, value2, "reason");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Byte value) {
			addCriterion("del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Byte value) {
			addCriterion("del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Byte value) {
			addCriterion("del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Byte value) {
			addCriterion("del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
			addCriterion("del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Byte> values) {
			addCriterion("del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Byte> values) {
			addCriterion("del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Byte value1, Byte value2) {
			addCriterion("del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_sign
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 18 02:16:06 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}