package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class TaskSign implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.id
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.task_id
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Integer taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.uid
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.bid_status
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Byte bidStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.bid_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Date bidTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.single_price
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private String singlePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.pay_status
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Byte payStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.pay_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.op_id
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Integer opId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.op_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Date opTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.reason
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.add_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.update_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task_sign.del_flag
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table task_sign
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.id
	 * @return  the value of task_sign.id
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.id
	 * @param id  the value for task_sign.id
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.task_id
	 * @return  the value of task_sign.task_id
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Integer getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.task_id
	 * @param taskId  the value for task_sign.task_id
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.uid
	 * @return  the value of task_sign.uid
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.uid
	 * @param uid  the value for task_sign.uid
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.bid_status
	 * @return  the value of task_sign.bid_status
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Byte getBidStatus() {
		return bidStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.bid_status
	 * @param bidStatus  the value for task_sign.bid_status
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setBidStatus(Byte bidStatus) {
		this.bidStatus = bidStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.bid_time
	 * @return  the value of task_sign.bid_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Date getBidTime() {
		return bidTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.bid_time
	 * @param bidTime  the value for task_sign.bid_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setBidTime(Date bidTime) {
		this.bidTime = bidTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.single_price
	 * @return  the value of task_sign.single_price
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public String getSinglePrice() {
		return singlePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.single_price
	 * @param singlePrice  the value for task_sign.single_price
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setSinglePrice(String singlePrice) {
		this.singlePrice = singlePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.pay_status
	 * @return  the value of task_sign.pay_status
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Byte getPayStatus() {
		return payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.pay_status
	 * @param payStatus  the value for task_sign.pay_status
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setPayStatus(Byte payStatus) {
		this.payStatus = payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.pay_time
	 * @return  the value of task_sign.pay_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.pay_time
	 * @param payTime  the value for task_sign.pay_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.op_id
	 * @return  the value of task_sign.op_id
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Integer getOpId() {
		return opId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.op_id
	 * @param opId  the value for task_sign.op_id
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setOpId(Integer opId) {
		this.opId = opId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.op_time
	 * @return  the value of task_sign.op_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Date getOpTime() {
		return opTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.op_time
	 * @param opTime  the value for task_sign.op_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.reason
	 * @return  the value of task_sign.reason
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.reason
	 * @param reason  the value for task_sign.reason
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.add_time
	 * @return  the value of task_sign.add_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.add_time
	 * @param addTime  the value for task_sign.add_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.update_time
	 * @return  the value of task_sign.update_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.update_time
	 * @param updateTime  the value for task_sign.update_time
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task_sign.del_flag
	 * @return  the value of task_sign.del_flag
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task_sign.del_flag
	 * @param delFlag  the value for task_sign.del_flag
	 * @mbggenerated  Mon Nov 07 18:32:20 GMT+08:00 2016
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}
}