package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mobile
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.passwd
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String passwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.pay_passwd
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String payPasswd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.nickname
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.avatar
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.balance
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String balance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.reg_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Date regTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.truename
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String truename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id_card
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String idCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.front_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String frontPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.back_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String backPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.hand_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String handPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.plat
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String plat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.live_room
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String liveRoom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.plat_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String platPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.auth_status
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Byte authStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.auth_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Date authTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.auth_opid
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Integer authOpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.contact_mobile
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String contactMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.contact_address
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String contactAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.agency_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String agencyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.agency_mobile
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String agencyMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.account_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String accountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.bank_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String bankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sub_bank_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String subBankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.bank_card
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String bankCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.task_cat
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String taskCat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.qq_id
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String qqId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.weixin_id
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String weixinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.description
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.note
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.cat_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Integer catNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sign_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Integer signNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.finish_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Integer finishNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.balance_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private String balanceNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.add_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.del_flag
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mobile
	 * @return  the value of user.mobile
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mobile
	 * @param mobile  the value for user.mobile
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.passwd
	 * @return  the value of user.passwd
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getPasswd() {
		return passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.passwd
	 * @param passwd  the value for user.passwd
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.pay_passwd
	 * @return  the value of user.pay_passwd
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getPayPasswd() {
		return payPasswd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.pay_passwd
	 * @param payPasswd  the value for user.pay_passwd
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setPayPasswd(String payPasswd) {
		this.payPasswd = payPasswd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.nickname
	 * @return  the value of user.nickname
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.nickname
	 * @param nickname  the value for user.nickname
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.avatar
	 * @return  the value of user.avatar
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.avatar
	 * @param avatar  the value for user.avatar
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.balance
	 * @return  the value of user.balance
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.balance
	 * @param balance  the value for user.balance
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setBalance(String balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.reg_time
	 * @return  the value of user.reg_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.reg_time
	 * @param regTime  the value for user.reg_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.truename
	 * @return  the value of user.truename
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getTruename() {
		return truename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.truename
	 * @param truename  the value for user.truename
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setTruename(String truename) {
		this.truename = truename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id_card
	 * @return  the value of user.id_card
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id_card
	 * @param idCard  the value for user.id_card
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.front_pic
	 * @return  the value of user.front_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getFrontPic() {
		return frontPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.front_pic
	 * @param frontPic  the value for user.front_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setFrontPic(String frontPic) {
		this.frontPic = frontPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.back_pic
	 * @return  the value of user.back_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getBackPic() {
		return backPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.back_pic
	 * @param backPic  the value for user.back_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setBackPic(String backPic) {
		this.backPic = backPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.hand_pic
	 * @return  the value of user.hand_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getHandPic() {
		return handPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.hand_pic
	 * @param handPic  the value for user.hand_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setHandPic(String handPic) {
		this.handPic = handPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.plat
	 * @return  the value of user.plat
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getPlat() {
		return plat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.plat
	 * @param plat  the value for user.plat
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setPlat(String plat) {
		this.plat = plat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.live_room
	 * @return  the value of user.live_room
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getLiveRoom() {
		return liveRoom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.live_room
	 * @param liveRoom  the value for user.live_room
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setLiveRoom(String liveRoom) {
		this.liveRoom = liveRoom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.plat_pic
	 * @return  the value of user.plat_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getPlatPic() {
		return platPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.plat_pic
	 * @param platPic  the value for user.plat_pic
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setPlatPic(String platPic) {
		this.platPic = platPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.auth_status
	 * @return  the value of user.auth_status
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Byte getAuthStatus() {
		return authStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.auth_status
	 * @param authStatus  the value for user.auth_status
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setAuthStatus(Byte authStatus) {
		this.authStatus = authStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.auth_time
	 * @return  the value of user.auth_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Date getAuthTime() {
		return authTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.auth_time
	 * @param authTime  the value for user.auth_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setAuthTime(Date authTime) {
		this.authTime = authTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.auth_opid
	 * @return  the value of user.auth_opid
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Integer getAuthOpid() {
		return authOpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.auth_opid
	 * @param authOpid  the value for user.auth_opid
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setAuthOpid(Integer authOpid) {
		this.authOpid = authOpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.contact_mobile
	 * @return  the value of user.contact_mobile
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getContactMobile() {
		return contactMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.contact_mobile
	 * @param contactMobile  the value for user.contact_mobile
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setContactMobile(String contactMobile) {
		this.contactMobile = contactMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.contact_address
	 * @return  the value of user.contact_address
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getContactAddress() {
		return contactAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.contact_address
	 * @param contactAddress  the value for user.contact_address
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setContactAddress(String contactAddress) {
		this.contactAddress = contactAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.agency_name
	 * @return  the value of user.agency_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getAgencyName() {
		return agencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.agency_name
	 * @param agencyName  the value for user.agency_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setAgencyName(String agencyName) {
		this.agencyName = agencyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.agency_mobile
	 * @return  the value of user.agency_mobile
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getAgencyMobile() {
		return agencyMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.agency_mobile
	 * @param agencyMobile  the value for user.agency_mobile
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setAgencyMobile(String agencyMobile) {
		this.agencyMobile = agencyMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.account_name
	 * @return  the value of user.account_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.account_name
	 * @param accountName  the value for user.account_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.bank_name
	 * @return  the value of user.bank_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.bank_name
	 * @param bankName  the value for user.bank_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sub_bank_name
	 * @return  the value of user.sub_bank_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getSubBankName() {
		return subBankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sub_bank_name
	 * @param subBankName  the value for user.sub_bank_name
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setSubBankName(String subBankName) {
		this.subBankName = subBankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.bank_card
	 * @return  the value of user.bank_card
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getBankCard() {
		return bankCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.bank_card
	 * @param bankCard  the value for user.bank_card
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setBankCard(String bankCard) {
		this.bankCard = bankCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.task_cat
	 * @return  the value of user.task_cat
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getTaskCat() {
		return taskCat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.task_cat
	 * @param taskCat  the value for user.task_cat
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setTaskCat(String taskCat) {
		this.taskCat = taskCat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.qq_id
	 * @return  the value of user.qq_id
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getQqId() {
		return qqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.qq_id
	 * @param qqId  the value for user.qq_id
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setQqId(String qqId) {
		this.qqId = qqId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.weixin_id
	 * @return  the value of user.weixin_id
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getWeixinId() {
		return weixinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.weixin_id
	 * @param weixinId  the value for user.weixin_id
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setWeixinId(String weixinId) {
		this.weixinId = weixinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.description
	 * @return  the value of user.description
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.description
	 * @param description  the value for user.description
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.note
	 * @return  the value of user.note
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.note
	 * @param note  the value for user.note
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.cat_num
	 * @return  the value of user.cat_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Integer getCatNum() {
		return catNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.cat_num
	 * @param catNum  the value for user.cat_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setCatNum(Integer catNum) {
		this.catNum = catNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sign_num
	 * @return  the value of user.sign_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Integer getSignNum() {
		return signNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sign_num
	 * @param signNum  the value for user.sign_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setSignNum(Integer signNum) {
		this.signNum = signNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.finish_num
	 * @return  the value of user.finish_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Integer getFinishNum() {
		return finishNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.finish_num
	 * @param finishNum  the value for user.finish_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setFinishNum(Integer finishNum) {
		this.finishNum = finishNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.balance_num
	 * @return  the value of user.balance_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getBalanceNum() {
		return balanceNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.balance_num
	 * @param balanceNum  the value for user.balance_num
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setBalanceNum(String balanceNum) {
		this.balanceNum = balanceNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.add_time
	 * @return  the value of user.add_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.add_time
	 * @param addTime  the value for user.add_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.update_time
	 * @return  the value of user.update_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.update_time
	 * @param updateTime  the value for user.update_time
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.del_flag
	 * @return  the value of user.del_flag
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.del_flag
	 * @param delFlag  the value for user.del_flag
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}
}