package org.bees.biz.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	protected int limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	protected int limitEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	protected String groupByClause;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public void setGroupByClause(String groupByClause) {
		this.groupByClause = groupByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public String getGroupByClause() {
		return groupByClause;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andPasswdIsNull() {
			addCriterion("passwd is null");
			return (Criteria) this;
		}

		public Criteria andPasswdIsNotNull() {
			addCriterion("passwd is not null");
			return (Criteria) this;
		}

		public Criteria andPasswdEqualTo(String value) {
			addCriterion("passwd =", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdNotEqualTo(String value) {
			addCriterion("passwd <>", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdGreaterThan(String value) {
			addCriterion("passwd >", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdGreaterThanOrEqualTo(String value) {
			addCriterion("passwd >=", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdLessThan(String value) {
			addCriterion("passwd <", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdLessThanOrEqualTo(String value) {
			addCriterion("passwd <=", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdLike(String value) {
			addCriterion("passwd like", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdNotLike(String value) {
			addCriterion("passwd not like", value, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdIn(List<String> values) {
			addCriterion("passwd in", values, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdNotIn(List<String> values) {
			addCriterion("passwd not in", values, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdBetween(String value1, String value2) {
			addCriterion("passwd between", value1, value2, "passwd");
			return (Criteria) this;
		}

		public Criteria andPasswdNotBetween(String value1, String value2) {
			addCriterion("passwd not between", value1, value2, "passwd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdIsNull() {
			addCriterion("pay_passwd is null");
			return (Criteria) this;
		}

		public Criteria andPayPasswdIsNotNull() {
			addCriterion("pay_passwd is not null");
			return (Criteria) this;
		}

		public Criteria andPayPasswdEqualTo(String value) {
			addCriterion("pay_passwd =", value, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdNotEqualTo(String value) {
			addCriterion("pay_passwd <>", value, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdGreaterThan(String value) {
			addCriterion("pay_passwd >", value, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdGreaterThanOrEqualTo(String value) {
			addCriterion("pay_passwd >=", value, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdLessThan(String value) {
			addCriterion("pay_passwd <", value, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdLessThanOrEqualTo(String value) {
			addCriterion("pay_passwd <=", value, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdLike(String value) {
			addCriterion("pay_passwd like", value, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdNotLike(String value) {
			addCriterion("pay_passwd not like", value, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdIn(List<String> values) {
			addCriterion("pay_passwd in", values, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdNotIn(List<String> values) {
			addCriterion("pay_passwd not in", values, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdBetween(String value1, String value2) {
			addCriterion("pay_passwd between", value1, value2, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andPayPasswdNotBetween(String value1, String value2) {
			addCriterion("pay_passwd not between", value1, value2, "payPasswd");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNull() {
			addCriterion("nickname is null");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNotNull() {
			addCriterion("nickname is not null");
			return (Criteria) this;
		}

		public Criteria andNicknameEqualTo(String value) {
			addCriterion("nickname =", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotEqualTo(String value) {
			addCriterion("nickname <>", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThan(String value) {
			addCriterion("nickname >", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("nickname >=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThan(String value) {
			addCriterion("nickname <", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThanOrEqualTo(String value) {
			addCriterion("nickname <=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLike(String value) {
			addCriterion("nickname like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotLike(String value) {
			addCriterion("nickname not like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameIn(List<String> values) {
			addCriterion("nickname in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotIn(List<String> values) {
			addCriterion("nickname not in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameBetween(String value1, String value2) {
			addCriterion("nickname between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotBetween(String value1, String value2) {
			addCriterion("nickname not between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andAvatarIsNull() {
			addCriterion("avatar is null");
			return (Criteria) this;
		}

		public Criteria andAvatarIsNotNull() {
			addCriterion("avatar is not null");
			return (Criteria) this;
		}

		public Criteria andAvatarEqualTo(String value) {
			addCriterion("avatar =", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotEqualTo(String value) {
			addCriterion("avatar <>", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarGreaterThan(String value) {
			addCriterion("avatar >", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarGreaterThanOrEqualTo(String value) {
			addCriterion("avatar >=", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarLessThan(String value) {
			addCriterion("avatar <", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarLessThanOrEqualTo(String value) {
			addCriterion("avatar <=", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarLike(String value) {
			addCriterion("avatar like", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotLike(String value) {
			addCriterion("avatar not like", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarIn(List<String> values) {
			addCriterion("avatar in", values, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotIn(List<String> values) {
			addCriterion("avatar not in", values, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarBetween(String value1, String value2) {
			addCriterion("avatar between", value1, value2, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotBetween(String value1, String value2) {
			addCriterion("avatar not between", value1, value2, "avatar");
			return (Criteria) this;
		}

		public Criteria andBalanceIsNull() {
			addCriterion("balance is null");
			return (Criteria) this;
		}

		public Criteria andBalanceIsNotNull() {
			addCriterion("balance is not null");
			return (Criteria) this;
		}

		public Criteria andBalanceEqualTo(String value) {
			addCriterion("balance =", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotEqualTo(String value) {
			addCriterion("balance <>", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceGreaterThan(String value) {
			addCriterion("balance >", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceGreaterThanOrEqualTo(String value) {
			addCriterion("balance >=", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceLessThan(String value) {
			addCriterion("balance <", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceLessThanOrEqualTo(String value) {
			addCriterion("balance <=", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceLike(String value) {
			addCriterion("balance like", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotLike(String value) {
			addCriterion("balance not like", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceIn(List<String> values) {
			addCriterion("balance in", values, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotIn(List<String> values) {
			addCriterion("balance not in", values, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceBetween(String value1, String value2) {
			addCriterion("balance between", value1, value2, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotBetween(String value1, String value2) {
			addCriterion("balance not between", value1, value2, "balance");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNull() {
			addCriterion("reg_time is null");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNotNull() {
			addCriterion("reg_time is not null");
			return (Criteria) this;
		}

		public Criteria andRegTimeEqualTo(Date value) {
			addCriterion("reg_time =", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotEqualTo(Date value) {
			addCriterion("reg_time <>", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThan(Date value) {
			addCriterion("reg_time >", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("reg_time >=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThan(Date value) {
			addCriterion("reg_time <", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThanOrEqualTo(Date value) {
			addCriterion("reg_time <=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeIn(List<Date> values) {
			addCriterion("reg_time in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotIn(List<Date> values) {
			addCriterion("reg_time not in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeBetween(Date value1, Date value2) {
			addCriterion("reg_time between", value1, value2, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotBetween(Date value1, Date value2) {
			addCriterion("reg_time not between", value1, value2, "regTime");
			return (Criteria) this;
		}

		public Criteria andTruenameIsNull() {
			addCriterion("truename is null");
			return (Criteria) this;
		}

		public Criteria andTruenameIsNotNull() {
			addCriterion("truename is not null");
			return (Criteria) this;
		}

		public Criteria andTruenameEqualTo(String value) {
			addCriterion("truename =", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotEqualTo(String value) {
			addCriterion("truename <>", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameGreaterThan(String value) {
			addCriterion("truename >", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameGreaterThanOrEqualTo(String value) {
			addCriterion("truename >=", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameLessThan(String value) {
			addCriterion("truename <", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameLessThanOrEqualTo(String value) {
			addCriterion("truename <=", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameLike(String value) {
			addCriterion("truename like", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotLike(String value) {
			addCriterion("truename not like", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameIn(List<String> values) {
			addCriterion("truename in", values, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotIn(List<String> values) {
			addCriterion("truename not in", values, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameBetween(String value1, String value2) {
			addCriterion("truename between", value1, value2, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotBetween(String value1, String value2) {
			addCriterion("truename not between", value1, value2, "truename");
			return (Criteria) this;
		}

		public Criteria andIdCardIsNull() {
			addCriterion("id_card is null");
			return (Criteria) this;
		}

		public Criteria andIdCardIsNotNull() {
			addCriterion("id_card is not null");
			return (Criteria) this;
		}

		public Criteria andIdCardEqualTo(String value) {
			addCriterion("id_card =", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotEqualTo(String value) {
			addCriterion("id_card <>", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardGreaterThan(String value) {
			addCriterion("id_card >", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardGreaterThanOrEqualTo(String value) {
			addCriterion("id_card >=", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLessThan(String value) {
			addCriterion("id_card <", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLessThanOrEqualTo(String value) {
			addCriterion("id_card <=", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLike(String value) {
			addCriterion("id_card like", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotLike(String value) {
			addCriterion("id_card not like", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardIn(List<String> values) {
			addCriterion("id_card in", values, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotIn(List<String> values) {
			addCriterion("id_card not in", values, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardBetween(String value1, String value2) {
			addCriterion("id_card between", value1, value2, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotBetween(String value1, String value2) {
			addCriterion("id_card not between", value1, value2, "idCard");
			return (Criteria) this;
		}

		public Criteria andFrontPicIsNull() {
			addCriterion("front_pic is null");
			return (Criteria) this;
		}

		public Criteria andFrontPicIsNotNull() {
			addCriterion("front_pic is not null");
			return (Criteria) this;
		}

		public Criteria andFrontPicEqualTo(String value) {
			addCriterion("front_pic =", value, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicNotEqualTo(String value) {
			addCriterion("front_pic <>", value, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicGreaterThan(String value) {
			addCriterion("front_pic >", value, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicGreaterThanOrEqualTo(String value) {
			addCriterion("front_pic >=", value, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicLessThan(String value) {
			addCriterion("front_pic <", value, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicLessThanOrEqualTo(String value) {
			addCriterion("front_pic <=", value, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicLike(String value) {
			addCriterion("front_pic like", value, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicNotLike(String value) {
			addCriterion("front_pic not like", value, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicIn(List<String> values) {
			addCriterion("front_pic in", values, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicNotIn(List<String> values) {
			addCriterion("front_pic not in", values, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicBetween(String value1, String value2) {
			addCriterion("front_pic between", value1, value2, "frontPic");
			return (Criteria) this;
		}

		public Criteria andFrontPicNotBetween(String value1, String value2) {
			addCriterion("front_pic not between", value1, value2, "frontPic");
			return (Criteria) this;
		}

		public Criteria andBackPicIsNull() {
			addCriterion("back_pic is null");
			return (Criteria) this;
		}

		public Criteria andBackPicIsNotNull() {
			addCriterion("back_pic is not null");
			return (Criteria) this;
		}

		public Criteria andBackPicEqualTo(String value) {
			addCriterion("back_pic =", value, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicNotEqualTo(String value) {
			addCriterion("back_pic <>", value, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicGreaterThan(String value) {
			addCriterion("back_pic >", value, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicGreaterThanOrEqualTo(String value) {
			addCriterion("back_pic >=", value, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicLessThan(String value) {
			addCriterion("back_pic <", value, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicLessThanOrEqualTo(String value) {
			addCriterion("back_pic <=", value, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicLike(String value) {
			addCriterion("back_pic like", value, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicNotLike(String value) {
			addCriterion("back_pic not like", value, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicIn(List<String> values) {
			addCriterion("back_pic in", values, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicNotIn(List<String> values) {
			addCriterion("back_pic not in", values, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicBetween(String value1, String value2) {
			addCriterion("back_pic between", value1, value2, "backPic");
			return (Criteria) this;
		}

		public Criteria andBackPicNotBetween(String value1, String value2) {
			addCriterion("back_pic not between", value1, value2, "backPic");
			return (Criteria) this;
		}

		public Criteria andHandPicIsNull() {
			addCriterion("hand_pic is null");
			return (Criteria) this;
		}

		public Criteria andHandPicIsNotNull() {
			addCriterion("hand_pic is not null");
			return (Criteria) this;
		}

		public Criteria andHandPicEqualTo(String value) {
			addCriterion("hand_pic =", value, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicNotEqualTo(String value) {
			addCriterion("hand_pic <>", value, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicGreaterThan(String value) {
			addCriterion("hand_pic >", value, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicGreaterThanOrEqualTo(String value) {
			addCriterion("hand_pic >=", value, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicLessThan(String value) {
			addCriterion("hand_pic <", value, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicLessThanOrEqualTo(String value) {
			addCriterion("hand_pic <=", value, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicLike(String value) {
			addCriterion("hand_pic like", value, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicNotLike(String value) {
			addCriterion("hand_pic not like", value, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicIn(List<String> values) {
			addCriterion("hand_pic in", values, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicNotIn(List<String> values) {
			addCriterion("hand_pic not in", values, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicBetween(String value1, String value2) {
			addCriterion("hand_pic between", value1, value2, "handPic");
			return (Criteria) this;
		}

		public Criteria andHandPicNotBetween(String value1, String value2) {
			addCriterion("hand_pic not between", value1, value2, "handPic");
			return (Criteria) this;
		}

		public Criteria andPlatIsNull() {
			addCriterion("plat is null");
			return (Criteria) this;
		}

		public Criteria andPlatIsNotNull() {
			addCriterion("plat is not null");
			return (Criteria) this;
		}

		public Criteria andPlatEqualTo(String value) {
			addCriterion("plat =", value, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatNotEqualTo(String value) {
			addCriterion("plat <>", value, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatGreaterThan(String value) {
			addCriterion("plat >", value, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatGreaterThanOrEqualTo(String value) {
			addCriterion("plat >=", value, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatLessThan(String value) {
			addCriterion("plat <", value, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatLessThanOrEqualTo(String value) {
			addCriterion("plat <=", value, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatLike(String value) {
			addCriterion("plat like", value, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatNotLike(String value) {
			addCriterion("plat not like", value, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatIn(List<String> values) {
			addCriterion("plat in", values, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatNotIn(List<String> values) {
			addCriterion("plat not in", values, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatBetween(String value1, String value2) {
			addCriterion("plat between", value1, value2, "plat");
			return (Criteria) this;
		}

		public Criteria andPlatNotBetween(String value1, String value2) {
			addCriterion("plat not between", value1, value2, "plat");
			return (Criteria) this;
		}

		public Criteria andLiveRoomIsNull() {
			addCriterion("live_room is null");
			return (Criteria) this;
		}

		public Criteria andLiveRoomIsNotNull() {
			addCriterion("live_room is not null");
			return (Criteria) this;
		}

		public Criteria andLiveRoomEqualTo(String value) {
			addCriterion("live_room =", value, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomNotEqualTo(String value) {
			addCriterion("live_room <>", value, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomGreaterThan(String value) {
			addCriterion("live_room >", value, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomGreaterThanOrEqualTo(String value) {
			addCriterion("live_room >=", value, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomLessThan(String value) {
			addCriterion("live_room <", value, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomLessThanOrEqualTo(String value) {
			addCriterion("live_room <=", value, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomLike(String value) {
			addCriterion("live_room like", value, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomNotLike(String value) {
			addCriterion("live_room not like", value, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomIn(List<String> values) {
			addCriterion("live_room in", values, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomNotIn(List<String> values) {
			addCriterion("live_room not in", values, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomBetween(String value1, String value2) {
			addCriterion("live_room between", value1, value2, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andLiveRoomNotBetween(String value1, String value2) {
			addCriterion("live_room not between", value1, value2, "liveRoom");
			return (Criteria) this;
		}

		public Criteria andPlatPicIsNull() {
			addCriterion("plat_pic is null");
			return (Criteria) this;
		}

		public Criteria andPlatPicIsNotNull() {
			addCriterion("plat_pic is not null");
			return (Criteria) this;
		}

		public Criteria andPlatPicEqualTo(String value) {
			addCriterion("plat_pic =", value, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicNotEqualTo(String value) {
			addCriterion("plat_pic <>", value, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicGreaterThan(String value) {
			addCriterion("plat_pic >", value, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicGreaterThanOrEqualTo(String value) {
			addCriterion("plat_pic >=", value, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicLessThan(String value) {
			addCriterion("plat_pic <", value, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicLessThanOrEqualTo(String value) {
			addCriterion("plat_pic <=", value, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicLike(String value) {
			addCriterion("plat_pic like", value, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicNotLike(String value) {
			addCriterion("plat_pic not like", value, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicIn(List<String> values) {
			addCriterion("plat_pic in", values, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicNotIn(List<String> values) {
			addCriterion("plat_pic not in", values, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicBetween(String value1, String value2) {
			addCriterion("plat_pic between", value1, value2, "platPic");
			return (Criteria) this;
		}

		public Criteria andPlatPicNotBetween(String value1, String value2) {
			addCriterion("plat_pic not between", value1, value2, "platPic");
			return (Criteria) this;
		}

		public Criteria andAuthStatusIsNull() {
			addCriterion("auth_status is null");
			return (Criteria) this;
		}

		public Criteria andAuthStatusIsNotNull() {
			addCriterion("auth_status is not null");
			return (Criteria) this;
		}

		public Criteria andAuthStatusEqualTo(Byte value) {
			addCriterion("auth_status =", value, "authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthStatusNotEqualTo(Byte value) {
			addCriterion("auth_status <>", value, "authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthStatusGreaterThan(Byte value) {
			addCriterion("auth_status >", value, "authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("auth_status >=", value, "authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthStatusLessThan(Byte value) {
			addCriterion("auth_status <", value, "authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthStatusLessThanOrEqualTo(Byte value) {
			addCriterion("auth_status <=", value, "authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthStatusIn(List<Byte> values) {
			addCriterion("auth_status in", values, "authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthStatusNotIn(List<Byte> values) {
			addCriterion("auth_status not in", values, "authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthStatusBetween(Byte value1, Byte value2) {
			addCriterion("auth_status between", value1, value2, "authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("auth_status not between", value1, value2,
					"authStatus");
			return (Criteria) this;
		}

		public Criteria andAuthTimeIsNull() {
			addCriterion("auth_time is null");
			return (Criteria) this;
		}

		public Criteria andAuthTimeIsNotNull() {
			addCriterion("auth_time is not null");
			return (Criteria) this;
		}

		public Criteria andAuthTimeEqualTo(Date value) {
			addCriterion("auth_time =", value, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthTimeNotEqualTo(Date value) {
			addCriterion("auth_time <>", value, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthTimeGreaterThan(Date value) {
			addCriterion("auth_time >", value, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("auth_time >=", value, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthTimeLessThan(Date value) {
			addCriterion("auth_time <", value, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthTimeLessThanOrEqualTo(Date value) {
			addCriterion("auth_time <=", value, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthTimeIn(List<Date> values) {
			addCriterion("auth_time in", values, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthTimeNotIn(List<Date> values) {
			addCriterion("auth_time not in", values, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthTimeBetween(Date value1, Date value2) {
			addCriterion("auth_time between", value1, value2, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthTimeNotBetween(Date value1, Date value2) {
			addCriterion("auth_time not between", value1, value2, "authTime");
			return (Criteria) this;
		}

		public Criteria andAuthOpidIsNull() {
			addCriterion("auth_opid is null");
			return (Criteria) this;
		}

		public Criteria andAuthOpidIsNotNull() {
			addCriterion("auth_opid is not null");
			return (Criteria) this;
		}

		public Criteria andAuthOpidEqualTo(Integer value) {
			addCriterion("auth_opid =", value, "authOpid");
			return (Criteria) this;
		}

		public Criteria andAuthOpidNotEqualTo(Integer value) {
			addCriterion("auth_opid <>", value, "authOpid");
			return (Criteria) this;
		}

		public Criteria andAuthOpidGreaterThan(Integer value) {
			addCriterion("auth_opid >", value, "authOpid");
			return (Criteria) this;
		}

		public Criteria andAuthOpidGreaterThanOrEqualTo(Integer value) {
			addCriterion("auth_opid >=", value, "authOpid");
			return (Criteria) this;
		}

		public Criteria andAuthOpidLessThan(Integer value) {
			addCriterion("auth_opid <", value, "authOpid");
			return (Criteria) this;
		}

		public Criteria andAuthOpidLessThanOrEqualTo(Integer value) {
			addCriterion("auth_opid <=", value, "authOpid");
			return (Criteria) this;
		}

		public Criteria andAuthOpidIn(List<Integer> values) {
			addCriterion("auth_opid in", values, "authOpid");
			return (Criteria) this;
		}

		public Criteria andAuthOpidNotIn(List<Integer> values) {
			addCriterion("auth_opid not in", values, "authOpid");
			return (Criteria) this;
		}

		public Criteria andAuthOpidBetween(Integer value1, Integer value2) {
			addCriterion("auth_opid between", value1, value2, "authOpid");
			return (Criteria) this;
		}

		public Criteria andAuthOpidNotBetween(Integer value1, Integer value2) {
			addCriterion("auth_opid not between", value1, value2, "authOpid");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andContactMobileIsNull() {
			addCriterion("contact_mobile is null");
			return (Criteria) this;
		}

		public Criteria andContactMobileIsNotNull() {
			addCriterion("contact_mobile is not null");
			return (Criteria) this;
		}

		public Criteria andContactMobileEqualTo(String value) {
			addCriterion("contact_mobile =", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileNotEqualTo(String value) {
			addCriterion("contact_mobile <>", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileGreaterThan(String value) {
			addCriterion("contact_mobile >", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileGreaterThanOrEqualTo(String value) {
			addCriterion("contact_mobile >=", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileLessThan(String value) {
			addCriterion("contact_mobile <", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileLessThanOrEqualTo(String value) {
			addCriterion("contact_mobile <=", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileLike(String value) {
			addCriterion("contact_mobile like", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileNotLike(String value) {
			addCriterion("contact_mobile not like", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileIn(List<String> values) {
			addCriterion("contact_mobile in", values, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileNotIn(List<String> values) {
			addCriterion("contact_mobile not in", values, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileBetween(String value1, String value2) {
			addCriterion("contact_mobile between", value1, value2,
					"contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileNotBetween(String value1, String value2) {
			addCriterion("contact_mobile not between", value1, value2,
					"contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactAddressIsNull() {
			addCriterion("contact_address is null");
			return (Criteria) this;
		}

		public Criteria andContactAddressIsNotNull() {
			addCriterion("contact_address is not null");
			return (Criteria) this;
		}

		public Criteria andContactAddressEqualTo(String value) {
			addCriterion("contact_address =", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressNotEqualTo(String value) {
			addCriterion("contact_address <>", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressGreaterThan(String value) {
			addCriterion("contact_address >", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressGreaterThanOrEqualTo(String value) {
			addCriterion("contact_address >=", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressLessThan(String value) {
			addCriterion("contact_address <", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressLessThanOrEqualTo(String value) {
			addCriterion("contact_address <=", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressLike(String value) {
			addCriterion("contact_address like", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressNotLike(String value) {
			addCriterion("contact_address not like", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressIn(List<String> values) {
			addCriterion("contact_address in", values, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressNotIn(List<String> values) {
			addCriterion("contact_address not in", values, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressBetween(String value1, String value2) {
			addCriterion("contact_address between", value1, value2,
					"contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressNotBetween(String value1, String value2) {
			addCriterion("contact_address not between", value1, value2,
					"contactAddress");
			return (Criteria) this;
		}

		public Criteria andAgencyNameIsNull() {
			addCriterion("agency_name is null");
			return (Criteria) this;
		}

		public Criteria andAgencyNameIsNotNull() {
			addCriterion("agency_name is not null");
			return (Criteria) this;
		}

		public Criteria andAgencyNameEqualTo(String value) {
			addCriterion("agency_name =", value, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameNotEqualTo(String value) {
			addCriterion("agency_name <>", value, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameGreaterThan(String value) {
			addCriterion("agency_name >", value, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameGreaterThanOrEqualTo(String value) {
			addCriterion("agency_name >=", value, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameLessThan(String value) {
			addCriterion("agency_name <", value, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameLessThanOrEqualTo(String value) {
			addCriterion("agency_name <=", value, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameLike(String value) {
			addCriterion("agency_name like", value, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameNotLike(String value) {
			addCriterion("agency_name not like", value, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameIn(List<String> values) {
			addCriterion("agency_name in", values, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameNotIn(List<String> values) {
			addCriterion("agency_name not in", values, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameBetween(String value1, String value2) {
			addCriterion("agency_name between", value1, value2, "agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyNameNotBetween(String value1, String value2) {
			addCriterion("agency_name not between", value1, value2,
					"agencyName");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileIsNull() {
			addCriterion("agency_mobile is null");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileIsNotNull() {
			addCriterion("agency_mobile is not null");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileEqualTo(String value) {
			addCriterion("agency_mobile =", value, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileNotEqualTo(String value) {
			addCriterion("agency_mobile <>", value, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileGreaterThan(String value) {
			addCriterion("agency_mobile >", value, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileGreaterThanOrEqualTo(String value) {
			addCriterion("agency_mobile >=", value, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileLessThan(String value) {
			addCriterion("agency_mobile <", value, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileLessThanOrEqualTo(String value) {
			addCriterion("agency_mobile <=", value, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileLike(String value) {
			addCriterion("agency_mobile like", value, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileNotLike(String value) {
			addCriterion("agency_mobile not like", value, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileIn(List<String> values) {
			addCriterion("agency_mobile in", values, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileNotIn(List<String> values) {
			addCriterion("agency_mobile not in", values, "agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileBetween(String value1, String value2) {
			addCriterion("agency_mobile between", value1, value2,
					"agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAgencyMobileNotBetween(String value1, String value2) {
			addCriterion("agency_mobile not between", value1, value2,
					"agencyMobile");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNull() {
			addCriterion("account_name is null");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNotNull() {
			addCriterion("account_name is not null");
			return (Criteria) this;
		}

		public Criteria andAccountNameEqualTo(String value) {
			addCriterion("account_name =", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotEqualTo(String value) {
			addCriterion("account_name <>", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThan(String value) {
			addCriterion("account_name >", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThanOrEqualTo(String value) {
			addCriterion("account_name >=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThan(String value) {
			addCriterion("account_name <", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThanOrEqualTo(String value) {
			addCriterion("account_name <=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLike(String value) {
			addCriterion("account_name like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotLike(String value) {
			addCriterion("account_name not like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameIn(List<String> values) {
			addCriterion("account_name in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotIn(List<String> values) {
			addCriterion("account_name not in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameBetween(String value1, String value2) {
			addCriterion("account_name between", value1, value2, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotBetween(String value1, String value2) {
			addCriterion("account_name not between", value1, value2,
					"accountName");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNull() {
			addCriterion("bank_name is null");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNotNull() {
			addCriterion("bank_name is not null");
			return (Criteria) this;
		}

		public Criteria andBankNameEqualTo(String value) {
			addCriterion("bank_name =", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotEqualTo(String value) {
			addCriterion("bank_name <>", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThan(String value) {
			addCriterion("bank_name >", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("bank_name >=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThan(String value) {
			addCriterion("bank_name <", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThanOrEqualTo(String value) {
			addCriterion("bank_name <=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLike(String value) {
			addCriterion("bank_name like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotLike(String value) {
			addCriterion("bank_name not like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameIn(List<String> values) {
			addCriterion("bank_name in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotIn(List<String> values) {
			addCriterion("bank_name not in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameBetween(String value1, String value2) {
			addCriterion("bank_name between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotBetween(String value1, String value2) {
			addCriterion("bank_name not between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameIsNull() {
			addCriterion("sub_bank_name is null");
			return (Criteria) this;
		}

		public Criteria andSubBankNameIsNotNull() {
			addCriterion("sub_bank_name is not null");
			return (Criteria) this;
		}

		public Criteria andSubBankNameEqualTo(String value) {
			addCriterion("sub_bank_name =", value, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameNotEqualTo(String value) {
			addCriterion("sub_bank_name <>", value, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameGreaterThan(String value) {
			addCriterion("sub_bank_name >", value, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("sub_bank_name >=", value, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameLessThan(String value) {
			addCriterion("sub_bank_name <", value, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameLessThanOrEqualTo(String value) {
			addCriterion("sub_bank_name <=", value, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameLike(String value) {
			addCriterion("sub_bank_name like", value, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameNotLike(String value) {
			addCriterion("sub_bank_name not like", value, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameIn(List<String> values) {
			addCriterion("sub_bank_name in", values, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameNotIn(List<String> values) {
			addCriterion("sub_bank_name not in", values, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameBetween(String value1, String value2) {
			addCriterion("sub_bank_name between", value1, value2, "subBankName");
			return (Criteria) this;
		}

		public Criteria andSubBankNameNotBetween(String value1, String value2) {
			addCriterion("sub_bank_name not between", value1, value2,
					"subBankName");
			return (Criteria) this;
		}

		public Criteria andBankCardIsNull() {
			addCriterion("bank_card is null");
			return (Criteria) this;
		}

		public Criteria andBankCardIsNotNull() {
			addCriterion("bank_card is not null");
			return (Criteria) this;
		}

		public Criteria andBankCardEqualTo(String value) {
			addCriterion("bank_card =", value, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardNotEqualTo(String value) {
			addCriterion("bank_card <>", value, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardGreaterThan(String value) {
			addCriterion("bank_card >", value, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardGreaterThanOrEqualTo(String value) {
			addCriterion("bank_card >=", value, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardLessThan(String value) {
			addCriterion("bank_card <", value, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardLessThanOrEqualTo(String value) {
			addCriterion("bank_card <=", value, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardLike(String value) {
			addCriterion("bank_card like", value, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardNotLike(String value) {
			addCriterion("bank_card not like", value, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardIn(List<String> values) {
			addCriterion("bank_card in", values, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardNotIn(List<String> values) {
			addCriterion("bank_card not in", values, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardBetween(String value1, String value2) {
			addCriterion("bank_card between", value1, value2, "bankCard");
			return (Criteria) this;
		}

		public Criteria andBankCardNotBetween(String value1, String value2) {
			addCriterion("bank_card not between", value1, value2, "bankCard");
			return (Criteria) this;
		}
		
		 public Criteria andTaskCatInSet(Integer values) {
        	addCriterion("task_cat", values, "taskCat");
	        return (Criteria)this;
			
		}

		public Criteria andTaskCatIsNull() {
			addCriterion("task_cat is null");
			return (Criteria) this;
		}

		public Criteria andTaskCatIsNotNull() {
			addCriterion("task_cat is not null");
			return (Criteria) this;
		}

		public Criteria andTaskCatEqualTo(String value) {
			addCriterion("task_cat =", value, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatNotEqualTo(String value) {
			addCriterion("task_cat <>", value, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatGreaterThan(String value) {
			addCriterion("task_cat >", value, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatGreaterThanOrEqualTo(String value) {
			addCriterion("task_cat >=", value, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatLessThan(String value) {
			addCriterion("task_cat <", value, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatLessThanOrEqualTo(String value) {
			addCriterion("task_cat <=", value, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatLike(String value) {
			addCriterion("task_cat like", value, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatNotLike(String value) {
			addCriterion("task_cat not like", value, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatIn(List<String> values) {
			addCriterion("task_cat in", values, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatNotIn(List<String> values) {
			addCriterion("task_cat not in", values, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatBetween(String value1, String value2) {
			addCriterion("task_cat between", value1, value2, "taskCat");
			return (Criteria) this;
		}

		public Criteria andTaskCatNotBetween(String value1, String value2) {
			addCriterion("task_cat not between", value1, value2, "taskCat");
			return (Criteria) this;
		}

		public Criteria andQqIdIsNull() {
			addCriterion("qq_id is null");
			return (Criteria) this;
		}

		public Criteria andQqIdIsNotNull() {
			addCriterion("qq_id is not null");
			return (Criteria) this;
		}

		public Criteria andQqIdEqualTo(String value) {
			addCriterion("qq_id =", value, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdNotEqualTo(String value) {
			addCriterion("qq_id <>", value, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdGreaterThan(String value) {
			addCriterion("qq_id >", value, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdGreaterThanOrEqualTo(String value) {
			addCriterion("qq_id >=", value, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdLessThan(String value) {
			addCriterion("qq_id <", value, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdLessThanOrEqualTo(String value) {
			addCriterion("qq_id <=", value, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdLike(String value) {
			addCriterion("qq_id like", value, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdNotLike(String value) {
			addCriterion("qq_id not like", value, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdIn(List<String> values) {
			addCriterion("qq_id in", values, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdNotIn(List<String> values) {
			addCriterion("qq_id not in", values, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdBetween(String value1, String value2) {
			addCriterion("qq_id between", value1, value2, "qqId");
			return (Criteria) this;
		}

		public Criteria andQqIdNotBetween(String value1, String value2) {
			addCriterion("qq_id not between", value1, value2, "qqId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdIsNull() {
			addCriterion("weixin_id is null");
			return (Criteria) this;
		}

		public Criteria andWeixinIdIsNotNull() {
			addCriterion("weixin_id is not null");
			return (Criteria) this;
		}

		public Criteria andWeixinIdEqualTo(String value) {
			addCriterion("weixin_id =", value, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdNotEqualTo(String value) {
			addCriterion("weixin_id <>", value, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdGreaterThan(String value) {
			addCriterion("weixin_id >", value, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdGreaterThanOrEqualTo(String value) {
			addCriterion("weixin_id >=", value, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdLessThan(String value) {
			addCriterion("weixin_id <", value, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdLessThanOrEqualTo(String value) {
			addCriterion("weixin_id <=", value, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdLike(String value) {
			addCriterion("weixin_id like", value, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdNotLike(String value) {
			addCriterion("weixin_id not like", value, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdIn(List<String> values) {
			addCriterion("weixin_id in", values, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdNotIn(List<String> values) {
			addCriterion("weixin_id not in", values, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdBetween(String value1, String value2) {
			addCriterion("weixin_id between", value1, value2, "weixinId");
			return (Criteria) this;
		}

		public Criteria andWeixinIdNotBetween(String value1, String value2) {
			addCriterion("weixin_id not between", value1, value2, "weixinId");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2,
					"description");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("note not between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andCatNumIsNull() {
			addCriterion("cat_num is null");
			return (Criteria) this;
		}

		public Criteria andCatNumIsNotNull() {
			addCriterion("cat_num is not null");
			return (Criteria) this;
		}

		public Criteria andCatNumEqualTo(Integer value) {
			addCriterion("cat_num =", value, "catNum");
			return (Criteria) this;
		}

		public Criteria andCatNumNotEqualTo(Integer value) {
			addCriterion("cat_num <>", value, "catNum");
			return (Criteria) this;
		}

		public Criteria andCatNumGreaterThan(Integer value) {
			addCriterion("cat_num >", value, "catNum");
			return (Criteria) this;
		}

		public Criteria andCatNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("cat_num >=", value, "catNum");
			return (Criteria) this;
		}

		public Criteria andCatNumLessThan(Integer value) {
			addCriterion("cat_num <", value, "catNum");
			return (Criteria) this;
		}

		public Criteria andCatNumLessThanOrEqualTo(Integer value) {
			addCriterion("cat_num <=", value, "catNum");
			return (Criteria) this;
		}

		public Criteria andCatNumIn(List<Integer> values) {
			addCriterion("cat_num in", values, "catNum");
			return (Criteria) this;
		}

		public Criteria andCatNumNotIn(List<Integer> values) {
			addCriterion("cat_num not in", values, "catNum");
			return (Criteria) this;
		}

		public Criteria andCatNumBetween(Integer value1, Integer value2) {
			addCriterion("cat_num between", value1, value2, "catNum");
			return (Criteria) this;
		}

		public Criteria andCatNumNotBetween(Integer value1, Integer value2) {
			addCriterion("cat_num not between", value1, value2, "catNum");
			return (Criteria) this;
		}

		public Criteria andSignNumIsNull() {
			addCriterion("sign_num is null");
			return (Criteria) this;
		}

		public Criteria andSignNumIsNotNull() {
			addCriterion("sign_num is not null");
			return (Criteria) this;
		}

		public Criteria andSignNumEqualTo(Integer value) {
			addCriterion("sign_num =", value, "signNum");
			return (Criteria) this;
		}

		public Criteria andSignNumNotEqualTo(Integer value) {
			addCriterion("sign_num <>", value, "signNum");
			return (Criteria) this;
		}

		public Criteria andSignNumGreaterThan(Integer value) {
			addCriterion("sign_num >", value, "signNum");
			return (Criteria) this;
		}

		public Criteria andSignNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("sign_num >=", value, "signNum");
			return (Criteria) this;
		}

		public Criteria andSignNumLessThan(Integer value) {
			addCriterion("sign_num <", value, "signNum");
			return (Criteria) this;
		}

		public Criteria andSignNumLessThanOrEqualTo(Integer value) {
			addCriterion("sign_num <=", value, "signNum");
			return (Criteria) this;
		}

		public Criteria andSignNumIn(List<Integer> values) {
			addCriterion("sign_num in", values, "signNum");
			return (Criteria) this;
		}

		public Criteria andSignNumNotIn(List<Integer> values) {
			addCriterion("sign_num not in", values, "signNum");
			return (Criteria) this;
		}

		public Criteria andSignNumBetween(Integer value1, Integer value2) {
			addCriterion("sign_num between", value1, value2, "signNum");
			return (Criteria) this;
		}

		public Criteria andSignNumNotBetween(Integer value1, Integer value2) {
			addCriterion("sign_num not between", value1, value2, "signNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumIsNull() {
			addCriterion("finish_num is null");
			return (Criteria) this;
		}

		public Criteria andFinishNumIsNotNull() {
			addCriterion("finish_num is not null");
			return (Criteria) this;
		}

		public Criteria andFinishNumEqualTo(Integer value) {
			addCriterion("finish_num =", value, "finishNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumNotEqualTo(Integer value) {
			addCriterion("finish_num <>", value, "finishNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumGreaterThan(Integer value) {
			addCriterion("finish_num >", value, "finishNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("finish_num >=", value, "finishNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumLessThan(Integer value) {
			addCriterion("finish_num <", value, "finishNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumLessThanOrEqualTo(Integer value) {
			addCriterion("finish_num <=", value, "finishNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumIn(List<Integer> values) {
			addCriterion("finish_num in", values, "finishNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumNotIn(List<Integer> values) {
			addCriterion("finish_num not in", values, "finishNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumBetween(Integer value1, Integer value2) {
			addCriterion("finish_num between", value1, value2, "finishNum");
			return (Criteria) this;
		}

		public Criteria andFinishNumNotBetween(Integer value1, Integer value2) {
			addCriterion("finish_num not between", value1, value2, "finishNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumIsNull() {
			addCriterion("balance_num is null");
			return (Criteria) this;
		}

		public Criteria andBalanceNumIsNotNull() {
			addCriterion("balance_num is not null");
			return (Criteria) this;
		}

		public Criteria andBalanceNumEqualTo(String value) {
			addCriterion("balance_num =", value, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumNotEqualTo(String value) {
			addCriterion("balance_num <>", value, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumGreaterThan(String value) {
			addCriterion("balance_num >", value, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumGreaterThanOrEqualTo(String value) {
			addCriterion("balance_num >=", value, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumLessThan(String value) {
			addCriterion("balance_num <", value, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumLessThanOrEqualTo(String value) {
			addCriterion("balance_num <=", value, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumLike(String value) {
			addCriterion("balance_num like", value, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumNotLike(String value) {
			addCriterion("balance_num not like", value, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumIn(List<String> values) {
			addCriterion("balance_num in", values, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumNotIn(List<String> values) {
			addCriterion("balance_num not in", values, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumBetween(String value1, String value2) {
			addCriterion("balance_num between", value1, value2, "balanceNum");
			return (Criteria) this;
		}

		public Criteria andBalanceNumNotBetween(String value1, String value2) {
			addCriterion("balance_num not between", value1, value2,
					"balanceNum");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(Byte value) {
			addCriterion("del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(Byte value) {
			addCriterion("del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(Byte value) {
			addCriterion("del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(Byte value) {
			addCriterion("del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
			addCriterion("del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<Byte> values) {
			addCriterion("del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<Byte> values) {
			addCriterion("del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(Byte value1, Byte value2) {
			addCriterion("del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbggenerated  Mon Nov 14 10:02:57 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 24 04:25:42 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}