package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class WalletRecharge implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_recharge.id
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_recharge.uid
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_recharge.money
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private String money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_recharge.status
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_recharge.order_id
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_recharge.pay_type
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private Byte payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_recharge.pay_time
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_recharge.add_time
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_recharge.update_time
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_recharge.id
	 * @return  the value of wallet_recharge.id
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_recharge.id
	 * @param id  the value for wallet_recharge.id
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_recharge.uid
	 * @return  the value of wallet_recharge.uid
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_recharge.uid
	 * @param uid  the value for wallet_recharge.uid
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_recharge.money
	 * @return  the value of wallet_recharge.money
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public String getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_recharge.money
	 * @param money  the value for wallet_recharge.money
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public void setMoney(String money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_recharge.status
	 * @return  the value of wallet_recharge.status
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_recharge.status
	 * @param status  the value for wallet_recharge.status
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_recharge.order_id
	 * @return  the value of wallet_recharge.order_id
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_recharge.order_id
	 * @param orderId  the value for wallet_recharge.order_id
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_recharge.pay_type
	 * @return  the value of wallet_recharge.pay_type
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public Byte getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_recharge.pay_type
	 * @param payType  the value for wallet_recharge.pay_type
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public void setPayType(Byte payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_recharge.pay_time
	 * @return  the value of wallet_recharge.pay_time
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_recharge.pay_time
	 * @param payTime  the value for wallet_recharge.pay_time
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_recharge.add_time
	 * @return  the value of wallet_recharge.add_time
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_recharge.add_time
	 * @param addTime  the value for wallet_recharge.add_time
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_recharge.update_time
	 * @return  the value of wallet_recharge.update_time
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_recharge.update_time
	 * @param updateTime  the value for wallet_recharge.update_time
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}