package org.bees.biz.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class WalletCash implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.id
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.uid
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.money
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private String money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.status
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.apply_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private Date applyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.op_id
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private Integer opId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.op_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private Date opTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.third_order_id
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private String thirdOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.reseaon
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private String reseaon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.add_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.update_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wallet_cash.del_flag
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private Byte delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wallet_cash
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.id
	 * @return  the value of wallet_cash.id
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.id
	 * @param id  the value for wallet_cash.id
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.uid
	 * @return  the value of wallet_cash.uid
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.uid
	 * @param uid  the value for wallet_cash.uid
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.money
	 * @return  the value of wallet_cash.money
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public String getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.money
	 * @param money  the value for wallet_cash.money
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setMoney(String money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.status
	 * @return  the value of wallet_cash.status
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.status
	 * @param status  the value for wallet_cash.status
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.apply_time
	 * @return  the value of wallet_cash.apply_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public Date getApplyTime() {
		return applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.apply_time
	 * @param applyTime  the value for wallet_cash.apply_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.op_id
	 * @return  the value of wallet_cash.op_id
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public Integer getOpId() {
		return opId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.op_id
	 * @param opId  the value for wallet_cash.op_id
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setOpId(Integer opId) {
		this.opId = opId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.op_time
	 * @return  the value of wallet_cash.op_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public Date getOpTime() {
		return opTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.op_time
	 * @param opTime  the value for wallet_cash.op_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.third_order_id
	 * @return  the value of wallet_cash.third_order_id
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public String getThirdOrderId() {
		return thirdOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.third_order_id
	 * @param thirdOrderId  the value for wallet_cash.third_order_id
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setThirdOrderId(String thirdOrderId) {
		this.thirdOrderId = thirdOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.reseaon
	 * @return  the value of wallet_cash.reseaon
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public String getReseaon() {
		return reseaon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.reseaon
	 * @param reseaon  the value for wallet_cash.reseaon
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setReseaon(String reseaon) {
		this.reseaon = reseaon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.add_time
	 * @return  the value of wallet_cash.add_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.add_time
	 * @param addTime  the value for wallet_cash.add_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.update_time
	 * @return  the value of wallet_cash.update_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.update_time
	 * @param updateTime  the value for wallet_cash.update_time
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wallet_cash.del_flag
	 * @return  the value of wallet_cash.del_flag
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public Byte getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wallet_cash.del_flag
	 * @param delFlag  the value for wallet_cash.del_flag
	 * @mbggenerated  Thu Sep 22 11:18:11 CST 2016
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}
}