package org.bees.biz.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bees.biz.persistence.model.LeaveMsg;
import org.bees.biz.persistence.model.LeaveMsgExample;

public interface LeaveMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    int countByExample(LeaveMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    int deleteByExample(LeaveMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    int insert(LeaveMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    int insertSelective(LeaveMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    List<LeaveMsg> selectByExample(LeaveMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    LeaveMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") LeaveMsg record, @Param("example") LeaveMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    int updateByExample(@Param("record") LeaveMsg record, @Param("example") LeaveMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(LeaveMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_msg
     *
     * @mbggenerated Tue Aug 30 11:11:37 GMT+08:00 2016
     */
    int updateByPrimaryKey(LeaveMsg record);
}