package org.bees.biz.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bees.biz.persistence.model.Live;
import org.bees.biz.persistence.model.LiveExample;

public interface LiveMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	int countByExample(LiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	int deleteByExample(LiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	int insert(Live record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	int insertSelective(Live record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	List<Live> selectByExample(LiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	Live selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") Live record,
			@Param("example") LiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") Live record,
			@Param("example") LiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(Live record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table live
	 * @mbggenerated  Thu Nov 10 17:12:03 GMT+08:00 2016
	 */
	int updateByPrimaryKey(Live record);
}