package org.bees.biz.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bees.biz.persistence.model.OrderLog;
import org.bees.biz.persistence.model.OrderLogExample;

public interface OrderLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    int countByExample(OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    int deleteByExample(OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    int insert(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    int insertSelective(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    List<OrderLog> selectByExample(OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    OrderLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") OrderLog record, @Param("example") OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    int updateByExample(@Param("record") OrderLog record, @Param("example") OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    int updateByPrimaryKeySelective(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbggenerated Thu Aug 25 04:28:06 CST 2016
     */
    int updateByPrimaryKey(OrderLog record);
}