package org.bees.biz.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bees.biz.persistence.model.Packages;
import org.bees.biz.persistence.model.PackagesExample;

public interface PackagesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int countByExample(PackagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int deleteByExample(PackagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int insert(Packages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int insertSelective(Packages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	List<Packages> selectByExampleWithBLOBs(PackagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	List<Packages> selectByExample(PackagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	Packages selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Packages record,
			@Param("example") PackagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") Packages record,
			@Param("example") PackagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int updateByExample(@Param("record") Packages record,
			@Param("example") PackagesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int updateByPrimaryKeySelective(Packages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(Packages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages
	 * @mbggenerated  Mon Nov 21 00:37:28 CST 2016
	 */
	int updateByPrimaryKey(Packages record);
}