package org.bees.biz.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bees.biz.persistence.model.Task;
import org.bees.biz.persistence.model.TaskExample;

public interface TaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	int countByExample(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	int deleteByExample(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	int insert(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	int insertSelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	List<Task> selectByExample(TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	Task selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") Task record,
			@Param("example") TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") Task record,
			@Param("example") TaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task
	 * @mbggenerated  Wed Aug 24 16:35:56 GMT+08:00 2016
	 */
	int updateByPrimaryKey(Task record);
}