package org.bees.biz.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bees.biz.persistence.model.TaskCategory;
import org.bees.biz.persistence.model.TaskCategoryExample;

public interface TaskCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    int countByExample(TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    int deleteByExample(TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    int insert(TaskCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    int insertSelective(TaskCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    List<TaskCategory> selectByExample(TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    TaskCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") TaskCategory record, @Param("example") TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    int updateByExample(@Param("record") TaskCategory record, @Param("example") TaskCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    int updateByPrimaryKeySelective(TaskCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_category
     *
     * @mbggenerated Thu Aug 18 03:37:31 CST 2016
     */
    int updateByPrimaryKey(TaskCategory record);
}