package org.bees.biz.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bees.biz.persistence.model.UserPic;
import org.bees.biz.persistence.model.UserPicExample;

public interface UserPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    int countByExample(UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    int deleteByExample(UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    int insert(UserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    int insertSelective(UserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    List<UserPic> selectByExample(UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    UserPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") UserPic record, @Param("example") UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    int updateByExample(@Param("record") UserPic record, @Param("example") UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(UserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated Thu Aug 11 10:55:13 GMT+08:00 2016
     */
    int updateByPrimaryKey(UserPic record);
}