package org.bees.biz.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bees.biz.persistence.model.WalletRecharge;
import org.bees.biz.persistence.model.WalletRechargeExample;

public interface WalletRechargeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	int countByExample(WalletRechargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	int deleteByExample(WalletRechargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	int insert(WalletRecharge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	int insertSelective(WalletRecharge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	List<WalletRecharge> selectByExample(WalletRechargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	WalletRecharge selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	int updateByExampleSelective(@Param("record") WalletRecharge record,
			@Param("example") WalletRechargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	int updateByExample(@Param("record") WalletRecharge record,
			@Param("example") WalletRechargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	int updateByPrimaryKeySelective(WalletRecharge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wallet_recharge
	 * @mbggenerated  Tue Oct 18 22:57:11 CST 2016
	 */
	int updateByPrimaryKey(WalletRecharge record);
}