#coding=utf-8

class GlobalKeys:
	# Redis的key统一管理，保证多个应用场景中不冲突
	# 未登录串
	NOT_LOGIN_RES= "{\"code\":600,\"messages\":[],\"data\":{}}"
	# Token无效
	NOT_TOKEN_RES= "{\"code\":500,\"messages\":[{\"id\":\"doAction\",\"message\":\"token无效\"}],\"data\":{}}"
	SEC_URL_KEYS = "__SEC_URL__"
	SEC_FUNC_KEYS = "__SEC_FUNC__"
	# 用户中心
	PASSPORT_LOGIN_KEY= "__PASSPORT_LOGIIN__"
	PASSPORT_LOGIN_ERROR_KEY= "__PASSPORT_LOGIIN_ERROR__"
	PASSPORT_REG_MCODE_KEY= "__PASSPORT_REG_MCODE__"
	PASSPORT_PWD_MCODE_KEY= "__PASSPORT_PWD_MCODE__"
	# 公司注册
	COMPANY_LOGIN_KEY= "__COMPANY_LOGIIN__"
	COMPANY_REG_MCODE_KEY= "__COMPANY_REG_MCODE__"
	# 短信限制
	SMS_IP_LIMIT= "__SMS_IP_LIMIT__"
	SMS_MOBILE_LIMIT= "__SMS_MOBILE_LIMIT__"
	# 公司排名
	COMPANY_CITY_RANK_KEY= "__COMPANY_CITY_RANK__"
	COMPANY_INDUSTRY_RANK_KEY= "__COMPANY_INDUSTRY_RANK__"
	# 设备_用户唯一性
	DEVKEY_USRID_CHECK_KEY= "__DEVKEY_SESSIONKEY_CHECK_KEY__"
	# 联系人手机信息修改
	HR_UPDATE_CONTACTPHONE_KEY= "__HR_UPDATE_CONTACTPHONE_KEY__"
	# 实名认证
	PAY_USER_BIND_KEY= "__PAY_USER_BIND_KEY__"
	# 新提现验证
	PAY_USER_NEW_CASH_KEY= "__PAY_USER_NEW_CASH_KEY__"
	#
	PAY_USER_CASH_KEY= "__PAY_USER_CASH_KEY__"
	# IM用户
	PUSH_USER_IM_KEY="__PUSH_USER_IM_KEY__"
	# 验证码
	VERIFY_CODE_KEY="__VERIFY_CODE__"
	# 作弊IP
	CHEAT_KEY="__CHEAT__"
	# OAuth2联合登录
	OAUTH_AUTH_CODE= "__OAUTH_AUTH_CODE__"
	OAUTH_ACCESS_TOKEN= "__OAUTH_ACCESS_TOKEN__"
	OAUTH_REFRESHACCESS_TOKEN= "__OAUTH_REFRESHACCESS_TOKEN__"
	# 二度人脉
	RELATION_2_FRIEND= "__NEW_RELATION_2_FRIEND__"
	# 一度人脉
	RELATION_FRIEND= "__RELATION_FRIEND__"
	# 共同好友
	MUTUAL_FRIEND= "__MUTUAL_FRIEND__"
	# 人脉用户
	RELATION_USR= "__RELATION_USR__"
	# 二度人脉的共同好友
	RELATION_2_FRIEND_MUTUAL= "__NEW_RELATION_2_FRIEND_MUTUAL__"
	MD5KEY = "LVTEA"
