document.writeln("<div class=\'header\'>");
document.writeln("<div class=\'container\'>");
document.writeln("<a href=\'index.html\' class=\'logo\'><img src=\'images/logo.png\' alt=\'LOGO\' /></a>");
document.writeln("<ul class=\'nav\'>");
document.writeln(" <li><a href=\'index.html\'>首页</a><i></i></li>");
document.writeln(" <li><a href=\'buyMeal.html\'>套餐购买</a><i></i></li>");
document.writeln("<li><a href=\'personal.html\'>个人页</a><i></i></li>");
document.writeln("  <li><a href=\'store.html\'>小商城</a><i></i></li>");
document.writeln("<li><a href=\'offer.html\'>悬赏任务</a><i></i></li>");
document.writeln(" <li><a href=\'about.html\'>关于bees</a><i></i></li>");
document.writeln("</ul>");
document.writeln(" <div class=\'fr\'>");
document.writeln("</div>");
document.writeln("<div class=\'clearfix\'></div>");
document.writeln("</div>");
document.writeln("</div>");