document.writeln("<!-- footer -->");
document.writeln("<div class=\'footer\'>");
document.writeln("    <!-- footer-top -->");
document.writeln("    <div class=\'footer-top\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <!-- left -->");
document.writeln("            <div class=\'left\'>");
document.writeln("                <p class=\'big\'><i class=\'icon-tel\'></i> 400-800-8010</p>");
document.writeln("                <p><i class=\'icon-email\'></i> bees@126.com</p>");
document.writeln("                <p><i class=\'icon-qq\'></i> 2943059518</p>");
document.writeln("                <p><i class=\'icon-addr\'></i> 北京市朝阳区先锋大道</p>");
document.writeln("            </div>");
document.writeln("            <!-- /left -->");
document.writeln("            <!-- right -->");
document.writeln("            <div class=\'right\'>");
document.writeln("                <dl>");
document.writeln("                    <dd>微信公众号</dd>");
document.writeln("                    <dt><img src=\'images/code_01.png\' alt=\'微信公众号\' /></dt>");
document.writeln("                </dl>");
document.writeln("                <dl>");
document.writeln("                    <dd>商业合作</dd>");
document.writeln("                    <dt><img src=\'images/code_02.png\' alt=\'商业合作\' /></dt>");
document.writeln("                </dl>");
document.writeln("            </div>");
document.writeln("            <!-- /right -->");
document.writeln("            <!-- friend-link -->");
document.writeln("            <dl class=\'friend-link\'>");
document.writeln("                <dt>友情链接</dt>");
document.writeln("                <dd id = 'links'>");
document.writeln("                    <a href=\'http://www.douyutv.com\'>斗鱼</a>");
document.writeln("                    <a href=\'http://www.huajiao.com/\'>花椒直播</a>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("            <!-- /friend-link -->");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!-- /footer-top -->");
document.writeln("    <!-- footer-bottom -->");
document.writeln("    <div class=\'footer-bottom\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <p>Copyright © 2014-2016 BEES.net</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!-- /footer-bottom -->");
document.writeln("</div>");
document.writeln("<!-- /footer -->");