/**
 * Created by chen on 2016/8/1.
 */
(function($){var iDialogHtml='<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">'+'<div class="modal-dialog">'+'<div class="modal-content">'+'<div class="modal-header">'+'<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>'+'<h4 class="modal-title"></h4>'+'</div>'+'<div class="modal-body"></div>'+'<div class="modal-footer"></div>'+'</div>'+'</div>'+'</div>';$.fn.hideDialog=function(callBack){$(this).on('hide.bs.modal',function(){if('undefined'!==typeof callBack&&'function'===typeof callBack)callBack();});$(this).modal('hide');};$.fn.showDialog=function(){$(this).modal('show');};$.fn.iDialog=function(options){if('undefined'===typeof this)return null;var iDialog=$(iDialogHtml);options=$.extend({'width':580,'title':'提示','id':'MyModel','showFlag':false,'ok':false,'cancel':false,'okFunc':function(){},'showFunc':function(){},'cancelFunc':function(){},'loadCancel':function(){},'buttons':{}},options);var param={_id:$.trim($(this).attr('id')),_title:$.trim($(this).attr('title')),_className:$.trim($(this).attr('class')),_content:iDialog.find('.modal-dialog').css({width:options.width})}
if('undefined'===typeof param._title||'string'!==typeof param._title)param._title=options.title;if('undefined'===typeof param._id||'string'!==typeof param._id)param._id=options.id;iDialog.attr({'id':param._id}).find('.modal-title').html(param._title).end().addClass(param._className).find('.modal-body').html($(this).html());if('undefined'!==typeof options.ok&&'string'===typeof options.ok){iDialog.find('.modal-footer').append($('<button type="button" class="btn btn-primary"></button>').on('click',function(){if('undefined'!==typeof options.okFunc&&'function'===typeof options.okFunc)options.okFunc(iDialog,param);}).text(options.ok));}
if('undefined'!==typeof options.cancel&&'string'===typeof options.cancel){iDialog.find('.modal-footer').append($('<button type="button" class="btn btn-default" data-dismiss="modal"></button>').text(options.cancel));}
if(!options.ok&&!options.cancel){iDialog.find('.modal-footer').hide();}
$(this).replaceWith(iDialog);function resetVertical(){param._content.stop(!0,!0).animate({'margin-top':($(window).height()-param._content.height())/3>0?($(window).height()-param._content.height())/3:0},200);}
iDialog.showDialog=function(){iDialog.modal();return iDialog;};iDialog.hideDialog=function(){iDialog.modal('hide');return iDialog;}
iDialog.setContent=function(title,value){if('undefined'!==typeof title&&''!=title)iDialog.find('.modal-title').html(title);if('undefined'!==typeof value&&''!=value)iDialog.find('.modal-body').html(value);return iDialog;};iDialog.on('shown.bs.modal',function(){resetVertical();});iDialog.on('hide.bs.modal',function(){if('undefined'!==typeof options.cancelFunc&&'function'===typeof options.cancelFunc)options.cancelFunc(iDialog,param);});if(options.showFlag){iDialog.modal('show');}
if('undefined'!==typeof options.loadCancel&&'function'===typeof options.loadCancel)options.loadCancel(iDialog,param);return iDialog;};$.fn.lastTimeDialog=function(options){if('undefined'===typeof this)return;options=$.extend({_time:5,_playTime:1000,_lastTimeBox:null,_beforeCallBack:function(){},_lastCallBack:function(){},_breakOffCallBack:function(){}},options);var _this=this,handle;$(this).on('shown.bs.modal',function(){lastTime();});$(this).on('hidden.bs.modal',function(){clearInterval(handle);if(null!=options._lastTimeBox&&'undefined'!==typeof options._lastTimeBox)options._lastTimeBox.text(options._time);if('undefined'!==typeof options._breakOffCallBack&&'function'===typeof options._breakOffCallBack)options._breakOffCallBack(_this,lastTime);});function lastTime(){var lastTime=options._time;handle=setInterval(function(){if(lastTime<0){clearInterval(handle);if('undefined'!==typeof options._lastCallBack&&'function'===typeof options._lastCallBack)options._lastCallBack(_this,lastTime);}else{if(null!=options._lastTimeBox&&'undefined'!==typeof options._lastTimeBox)options._lastTimeBox.text(lastTime);if('undefined'!==typeof options._beforeCallBack&&'function'===typeof options._beforeCallBack)options._beforeCallBack(_this,lastTime);}
lastTime--;},options._playTime)}
return this;};$.fn.fnPageList=function(options){options=$.extend({newClassName:'row',column:4,child:'dl'},options);if('undefined'===typeof this)return undefined;var list=$(this);var listDl=$(this).find(options.child);if('undefined'!=typeof $(this).data('column'))options.column=parseInt($(this).data('column'));for(var i=0;i<listDl.length;i+=options.column){for(var j=i,newDiv=$('<div '+(options.newClassName!=''?'class='+options.newClassName:'')+' />');j<i+options.column&&j<listDl.length;j++){newDiv.append(listDl[j]);}
list.append(newDiv.append('<div class=clearfix></div>'));}
return this;};$.fn.myPaginate=function(options){var _this=this,_rows=[],_beforeHtml='',_numberHtml='',_firstHtml='',_lastHtml='',_numberList=[],_type={_fullType:"fulPage",_ajax:"ajax"};options=$.extend({_rows:5,_this:this,_parent:$(this).parent(),_childTag:$(this).find('.list'),_paging:null,_showNumber:6,_lastShowNumber:true,_showBefore:false,_showFirst:true,_showLast:true,_showType:_type._ajax,_ajaxUrl:'',_ajax:function(data){},_ajaxData:{},_paginateClassName:{_wrapper:'paging',_before:'paginateInfo',_number:'number_wrapper',_ellipsis:'ellipsis',_first:'first',_previous:'previous',_next:'next',_last:'last'},_paginate:{_beforeHtml:'当前第{offset}－{count}条 共计{total}条',_first:'首页',_previous:'上一页',_next:'下一页',_last:'尾页'},_total:0,_count:0,_offset:0},options);if('undefined'==typeof options._parent.find('div.'+options._paginateClassName._wrapper)[0]){options._parent.append($('<div class="'+options._paginateClassName._wrapper+'" />'));}
options._paging=options._parent.find('.'+options._paginateClassName._wrapper);if(_type._fullType==options._showType){options._total=options._childTag.children().size();}else if(_type._ajax==options._showType){}
if(_type._fullType==options._showType){for(var i=0,child=options._childTag.children();i<options._total;i++){_rows[i]=child.get(i);}}
options._childTag.html('');getPageCount();this.getOffset=function(){return options._offset;}
this.setAjaxData=function(_data){if('undefined'!=typeof _data&&'object'==typeof _data)options._ajaxData=$.extend(options._ajaxData,_data);}
this.getAjaxData=function(){return options._ajaxData;}
this.setOptions=function(opt){options=$.extend(options,opt),getPageCount(),setPaginate();}
function getPageCount(){options._count=Math.ceil(options._total/options._rows);}
function loadAjax(){if(_type._ajax==options._showType&&'undefined'!=typeof options._ajax&&'function'==typeof options._ajax){options._ajax(_this,$.extend(options._ajaxData,{total:options._total,rows:options._rows,offset:options._offset}),options._ajaxUrl);}}
function showRows(){loadAjax();if(_type._fullType==options._showType){for(var i=options._offset*options._rows,_max=(options._offset+1)*options._rows,_childBody=options._childTag.html('');i<_max&&i<options._total;i++)_childBody.append(_rows[i]);}}
showRows();function getNumberList(){for(var a=options._offset-Math.floor(options._showNumber/2),i=a<=0||options._count<=options._showNumber?0:a,j=i+options._showNumber-options._lastShowNumber,k=0,_numberList=[];i<options._count-options._lastShowNumber&&i<j;i++){_numberList[k++]=i;}
if(_numberList.length<options._showNumber-options._lastShowNumber&&options._count>options._showNumber&&_numberList[_numberList.length-1]==options._count-options._lastShowNumber-1){for(var i=options._count-options._showNumber,k=0;i<options._count-options._lastShowNumber;i++){_numberList[k++]=i;}}
return _numberList;}
function isEdge(){if(options._offset==_numberList[0]||options._offset==_numberList[_numberList.length-1]||options._offset==options._count-1||options._offset==0)return true;return false;}
function getNumber(){_numberList=getNumberList();_numberHtml='<span class="'+options._paginateClassName._number+'">';if(_numberList[0]>0)_numberHtml+='<span class="'+options._paginateClassName._ellipsis+'">...</span>';for(var i=0;i<_numberList.length;i++){if(_numberList[i]==options._offset){_numberHtml+='<a href="javascript:;"  checked="true" data-offset="'+_numberList[i]+'">'+(_numberList[i]+1)+'</a>'}else{_numberHtml+='<a href="javascript:;" data-offset="'+_numberList[i]+'">'+(_numberList[i]+1)+'</a>'}}
if(_numberList[_numberList.length-1]<options._count-2)_numberHtml+='<span class="'+options._paginateClassName._ellipsis+'">...</span>';if(options._lastShowNumber)_numberHtml+='<a href="javascript:;" '+(options._offset==options._count-1?'checked="true"':'')+' data-offset="'+(options._count-1)+'">'+options._count+'</a>';_numberHtml+='</span>';}
function replaceTag(_str,_data){if(!$.isArray(_data))return;for(var i=0,_html=_str;i<_data.length;i++){_html=_html.replace(new RegExp(''+_data[i].tag,'gm'),_data[i].value);}
return _html;}
_firstHtml=(options._showFirst?'<a class="'+options._paginateClassName._first+'" href="javascript:;">'+options._paginate._first+'</a>':'')+'<a class="'+options._paginateClassName._previous+'" href="javascript:;">'+options._paginate._previous+'</a>';_lastHtml='<a href="javascript:;" class="'+options._paginateClassName._next+'">'+options._paginate._next+'</a>'+(options._showLast?'<a href="javascript:;" class="'+options._paginateClassName._last+'">'+options._paginate._last+'</a>':'');function getBefore(){var _data=[{tag:'{total}',value:options._total},{tag:'{count}',value:options._count},{tag:'{offset}',value:(options._offset+1)}]
_beforeHtml=options._showBefore&&options._total?'<span class="'+options._paginateClassName._before+'">'+replaceTag(options._paginate._beforeHtml,_data)+'</span>':'';}
function setPaginate(){getBefore();if(options._count>1){getNumber(),options._paging.html(_firstHtml+_numberHtml+_lastHtml+_beforeHtml);if(options._offset==0){removeFirst();}else if(options._offset==options._count-1){removeLast();}}else{options._paging.html(_beforeHtml);}
loadEvent();}
setPaginate();loadEvent();function removeFirst(){options._paging.find('a.'+options._paginateClassName._first).removeAttr('href').attr('disabled',true);options._paging.find('a.'+options._paginateClassName._previous).removeAttr('href').attr('disabled',true);}
function addFirst(){options._paging.find('a.'+options._paginateClassName._first).attr('href','javascript:;').attr('disabled',false);options._paging.find('a.'+options._paginateClassName._previous).attr('href','javascript:;').attr('disabled',false);}
function removeLast(){options._paging.find('a.'+options._paginateClassName._next).removeAttr('href').attr('disabled',true);options._paging.find('a.'+options._paginateClassName._last).removeAttr('href').attr('disabled',true);}
function addLast(){options._paging.find('a.'+options._paginateClassName._next).attr('href','javascript:;').attr('disabled',false);options._paging.find('a.'+options._paginateClassName._last).attr('href','javascript:;').attr('disabled',false);}
function cutNumber(){if(isEdge()){setPaginate();}else{options._paging.find('a[data-offset]').removeAttr('checked').each(function(){if(parseInt($(this).data('offset'))==options._offset){$(this).attr('checked',true);}});}
getBefore();$('.'+options._paginateClassName._before).replaceWith(_beforeHtml);}
function loadEvent(){options._paging.find('a.'+options._paginateClassName._first).on('click',function(){if('undefined'!=typeof $(this).attr('href'))options._offset=0,cutNumber(),showRows();});options._paging.find('a.'+options._paginateClassName._previous).on('click',function(){if('undefined'!=typeof $(this).attr('href'))options._offset=options._offset-1<=0?0:options._offset-1,cutNumber(),showRows()});options._paging.find('a[data-offset]').on('click',function(){options._offset=$(this).data('offset');if(options._offset==0){addLast(),removeFirst();}else if(options._offset==options._count-1){addFirst(),removeLast();}else{addFirst(),addLast();}
cutNumber(),showRows();});options._paging.find('a.'+options._paginateClassName._next).on('click',function(){if('undefined'!=typeof $(this).attr('href'))options._offset=options._offset+1>=options._count?options._count-1:options._offset+1,cutNumber(),showRows();});options._paging.find('a.'+options._paginateClassName._last).on('click',function(){if('undefined'!=typeof $(this).attr('href'))options._offset=options._count-1,cutNumber(),showRows();});}
return this;};})(jQuery);